### ISSUE TITLE
Bandpass filtering and downsampling for HMM-TDE

### ISSUE THREAD

**Issue by FreektenDoesschate** [OHBA-analysis/HMM-MAR#102]
Dear dr. Vidaurre,

Thank you for developing this wonderful toolbox!

My question concerns the need for downsampling when using a band-pass filter. In case of a MAR emission model, the user guide suggests to downsample to double the frequency cutoff if a bandpass filter is applied.

First, could you give some intuition (or a literature ref) for why this is needed? Second, does this recommendation also hold for a HMM-TDE model?

Thank you in advance for your time.

Best,
Frederik

**Comment by NinaOmejc** [comment]
Dear dr.  Vidaurre,

i'd like to expand the upper question as I have a similar issue based on your wiki recommendation not to use the sampling frequency more than the double of the higest frequency in the (filtered) data.
I would like to use your method to infer states from both EEG and EMG data. For that, we concatenated the data by resampling both of the streams to 1000 Hz. EMG data was then low pass filtered to 500 Hz and EEG low pass filtered to 100 Hz. Based on your experience and knowledge, would you recommend running hmm on such data? 

Thank you very much for any comments.
Best,
Nina

**Comment by vidaurre** [comment]
Hi, 

@FreektenDoesschate : With respect to the first question, I think it's mostly empirical and the most important thing is to check the data before feeding it to the model inference, and after the preprocessing steps hve been carried out. For example to see if there are artefacts at the edges of the time series. I believe the interaction between mdoel estimation and distorting band pass filtering would apply to both models, but the MAR tends to be a bit more mercurial —so perhaps the TDE is more resilient to that kind of issues. 

@NinaOmejc : I guess it depends on the kind of features you would expect to find. Maybe an easier analysis to start with would be run the HMM on the EEG and the EMG separately, and then see if you find a coupling between the chains and where (using tools from information theory for example). You can model them together but the model, as it is, would not find cross-frequency, nonlinear interactions, which is what you might be after. 

Thanks
d
