### ISSUE TITLE
Error using tucacv function when setting the classifier to logistic?

### ISSUE THREAD

**Issue by felcshallot-1986** [OHBA-analysis/HMM-MAR#103]
I set the classifier to the logistic and tried the tucacv function but got the error like this:

"Function or variable 'ndim_n' not recognized"

Error in obsinit>initpost (line 363)
repmat(hmm.state(k).alpha.Gam_rate(1:ndim_n,end),1,train.logisticYdim);

Error in obsinit (line 27)
hmm = initpost(data.X,T,hmm,residuals,Gamma);

Error in hmmmar (line 410)
[hmm,residuals] = obsinit(data,T,hmm,GammaInit);

Error in tudatrain (line 165)
tuda = hmmmar(Z,T,options);

Error in tudacv (line 196)
[tuda,Gammatrain] = tudatrain(Xtrain,Ytrain,Ttr,options,options.K==1);

Error in tucacv (line 9)
[acc,acc_star,Ypred,Ypred_star,Gammapred,acc_Gamma] = tudacv(X,Y,T,options);

But it works well when I set the classifier to "LDA". Are there any problems there?

Best,
Horace

**Comment by CameronHiggins** [comment]
Hi Horace, 

My apologies for this, I have just patched a small bug fix. If you git pull a copy of the latest code this error should be resolved.

Thanks,
Cameron

**Comment by CameronHiggins** [comment]
See previous
