### ISSUE TITLE
Clarification on the Correct Approach to "Split-Half" for Choosing Number of States

### ISSUE THREAD

**Issue by SJFan** [OHBA-analysis/HMM-MAR#109]
Firstly, I want to express my gratitude for the development of this toolbox. It has been incredibly useful in my work. I have a new question and I apologize if it has been addressed in previous issues or documentation. I have reviewed them but I want to confirm if my understanding is correct.

From what I have learned, there are at least four factors that are relevant when setting the number of states: a. no redundant states, b. lower Free Energy, c. higher Reproducibility, and d. testing the index in a range of the number of states.

Based on my understanding, I can choose the number of states that are most reproducible when there are no redundant states. Concurrently, I also need to validate my final results within a range of the number of states. As for the Free Energy, I understand that I can consider it as a secondary check. Could you confirm if this is the correct approach?

Regarding reproducibility, my understanding is that I need to manually split the data (potentially using cvpartition multiple times), run the HMM separately, and check the similarity between the two subsets for gamma similarity. I can also test other characteristics that I am interested in, such as activation maps, functional connectivity, or Transition Probability Matrix (TPM). This approach is based on the NeuroImage 2018 paper. However, I haven't been able to locate the corresponding code. I understand that I can't simply use the cvhmmar function because it estimates the state time courses for the left-out data (without modifying the states) and obtains the data likelihood or the fractional error.

I appreciate your guidance on this matter. Thank you in advance for your time and assistance.

**Comment by vidaurre** [comment]
Hi — what you say makes sense. I am not sure we have public code to do the half splits, but cvhmmmar wouldn't be appropriate. The important thing is that you align the states across the two runs using the munkres function. The comparisons then should be straightforward.

Regarding reproducibility, worth checking this: https://direct.mit.edu/netn/article/doi/10.1162/netn_a_00331/117172/Towards-stability-of-dynamic-FC-estimates-in  
That is, maybe run it several times and choose the one with the lowest free energy.
