### ISSUE TITLE
checkGamma.m variable `d` undefined 

### ISSUE THREAD

**Issue by ReinderVosDeWael** [OHBA-analysis/HMM-MAR#11]
The if-statement ranging lines 9-17 in script `checkGamma.m` does not define variable `d` in its else-statement. When this occurs, line 20 `t = t + i*d;` throws an error because `d` has not been defined.

**Comment by vidaurre** [comment]
Thank you! I'll check it out

**Comment by vidaurre** [comment]
Corrected now
