### ISSUE TITLE
Help with getFuncConn and hmmdual (The diagonal of my correlation matrix is -1)

### ISSUE THREAD

**Issue by Ricwan4** [OHBA-analysis/HMM-MAR#116]
Hello! I recently encountered one issue regarding the getFuncConn function. After I did dual estimation and got the individual-wise HMM, I then would like to see the individual FC. However, it seems that for some participants I got -1 for the diagonal of my correlation matrix.

I tried to go over the code to see what was happening. I found out that it's because I got negative values for my diagonal in the covariance matrix. And that's because in the getFnucConn function line 43:

covmat = hmm.state(k).Omega.Gam_rate / (hmm.state(k).Omega.Gam_shape-ndim-1);

the (hmm.state(k).Omega.Gam_shape-ndim-1); part produced a **negative value.** 

I think this is due to the problem in hmmdual where something is wrong with the re-estimation of the gamma shape. So I then go check in the hmmdual function. I found out that the line where it seems to have gone wrong is updateOmega (in line 33 in obsupdate, and in line 122 in hmmdual).

I am not entirely sure what went wrong. Here is also my input to hmmdual. I think maybe I enter something wrong here:

 [Individual_hmm, Gamma] = hmmdual(current_data, current_T, hmm);

Current_data is a struct with one cell with a shape of 480 * 17, and the current_T is 480. This is the data for that one participant. hmm is a group level hmm that fit on the entire group (74 individuals, so 480*74*17, that's 35520*17).

Any input is greatly appreciated.

Eric

**Comment by deyuwang126** [comment]
Hi, Eric

I had the same problem with the **CORRMAT** diagonal with a -1, which I only knew was due to a negative number in the **COVMAT**, but I found that between the repetitions of the HMM inferences, some of the inferences did not showed the issue, so it may be a calculation error？

Best

deyu
