### ISSUE TITLE
Error running hmmmar in example code

### ISSUE THREAD

**Issue by mhgodfrey** [OHBA-analysis/HMM-MAR#12]
Hi, I've run into this error running the example code in the wiki, when the hmmmar function is called. I was wondering if anyone knows what might be causing it? Thanks

Error using hmmmar_init (line 33)
obslike function is giving trouble - Out of precision?

Error in hmmmar (line 296)
                [GammaInit,fehistInit] = hmmmar_init(data,T,options,Sind);
file:///home/c1655080/data/Entropy/Absence/HMM/demo.m

Error in demo (line 71)
[hmm, Gamma, Xi, vpath] = hmmmar(X,T,options);

**Comment by mhgodfrey** [comment]
Update - fixed by clearing matlab path

**Comment by vidaurre** [comment]
Sorry I didn't respond to this in time.
