### ISSUE TITLE
The error from Function getFuncConn

### ISSUE THREAD

**Issue by YingHe0** [OHBA-analysis/HMM-MAR#13]
Hi, Dr.Vidaurre! When I used the Function getFuncConn(hmm,k) to get correlation matrixs of some states, Matlab reported some errors:
`Error using corrcov (line 24)
C must be a square, symmetric, positive semidefinite matrix.

Error in getFuncConn (line 23)
corrmat = corrcov(covmat);`
 
Could you please help me to solve this problem? Thank you very much!

**Comment by vidaurre** [comment]
This is not really a solvable error. States that had very little data (or no data at all) assigned at the end of the inference might have not very well defined covariance matrices. I have made the report of the error more legible.
