### ISSUE TITLE
Issue with wiki example

### ISSUE THREAD

**Issue by didiermonselesan** [OHBA-analysis/HMM-MAR#15]
Diego,

An issue arises when executing the wiki examples (R2018b on Ubuntu 18.04 LTS).
Note that I have switch off parallelisation (with options.useParallel=0).

The logical indices in position 1 contain a true value outside of the array bounds, when executing this snippet

% Training a HMM model with Gaussian states:

    options = struct();
    options.K = K; 
    options.Fs = Fs; 
    options.covtype = 'full';
    options.order = 0;
    options.DirichletDiag = 2; 
    options.zeromean = 0;
    options.verbose = 1;
    options.useParallel=0;

    [hmm, Gamma, Xi, vpath] = hmmmar(X,T,options);

Thanks for making your work available.

Cheers, Didier
------------------------------------------------------------------------------------------------------------------------
Here is a dump of the examples standard output up to the line 

 [hmm, Gamma, Xi, vpath] = hmmmar(X,T,options);

>> Examples
Run 1, Init, score 28.700009 
Run 1, Cycle 1, score +10.600151, flipped (3,2) 
Run 1, Cycle 2, score +8.630549, flipped (2,1) 
Run 1, Cycle 3, score +5.300925, flipped (6,3) 
Run 1, Cycle 4, score +4.719295, flipped (4,3) 
Run 1, Cycle 5, score +0
Run 1, Cycle 6, score +0
Run 1, Cycle 7, score +0
Run 1, Cycle 8, score +0
Run 1, Cycle 9, score +0
Convergence, score=57.950929 
Run 2, Init, score 18.418133 
Run 2, Cycle 1, score +10.145189, flipped (3,2) 
Run 2, Cycle 2, score +9.991239, flipped (7,2) 
Run 2, Cycle 3, score +9.056330, flipped (8,2) 
Run 2, Cycle 4, score +5.620743, flipped (2,3) 
Run 2, Cycle 5, score +4.719295, flipped (4,3) 
Run 2, Cycle 6, score +0
Run 2, Cycle 7, score +0
Run 2, Cycle 8, score +0
Run 2, Cycle 9, score +0
Convergence, score=57.950929 
Run 3, Init, score 29.491665 
Run 3, Cycle 1, score +6.230094, flipped (6,1) 
Run 3, Cycle 2, score +6.715401, flipped (5,1) 
Run 3, Cycle 3, score +5.406204, flipped (2,3) 
Run 3, Cycle 4, score +5.388271, flipped (8,3) 
Run 3, Cycle 5, score +4.719295, flipped (4,3) 
Run 3, Cycle 6, score +0
Run 3, Cycle 7, score +0
Run 3, Cycle 8, score +0
Run 3, Cycle 9, score +0
Convergence, score=57.950929 
Run 4, Init, score 6.179333 
Run 4, Cycle 1, score +11.942237, flipped (9,2) 
Run 4, Cycle 2, score +4.791364, flipped (1,1) 
Run 4, Cycle 3, score +4.198299, flipped (10,1) 
Run 4, Cycle 4, score +8.575419, flipped (8,1) 
Run 4, Cycle 5, score +7.736708, flipped (6,1) 
Run 4, Cycle 6, score +5.007560, flipped (3,3) 
Run 4, Cycle 7, score +4.800714, flipped (7,3) 
Run 4, Cycle 8, score +4.719295, flipped (4,3) 
Run 4, Cycle 9, score +0
Convergence, score=57.950929 
Run 5, Init, score 19.905472 
Run 5, Cycle 1, score +10.600151, flipped (3,2) 
Run 5, Cycle 2, score +9.991239, flipped (7,2) 
Run 5, Cycle 3, score +8.751428, flipped (10,1) 
Run 5, Cycle 4, score +8.702639, flipped (2,1) 
Run 5, Cycle 5, score +0
Run 5, Cycle 6, score +0
Run 5, Cycle 7, score +0
Run 5, Cycle 8, score +0
Run 5, Cycle 9, score +0
Convergence, score=57.950929 
Run 6, Init, score 16.944421 
Run 6, Cycle 1, score +6.553550, flipped (8,1) 
Run 6, Cycle 2, score +8.702639, flipped (2,1) 
Run 6, Cycle 3, score +8.126697, flipped (3,1) 
Run 6, Cycle 4, score +7.829878, flipped (1,1) 
Run 6, Cycle 5, score +5.300925, flipped (6,3) 
Run 6, Cycle 6, score +4.492819, flipped (9,3) 
Run 6, Cycle 7, score +0
Run 6, Cycle 8, score +0
Run 6, Cycle 9, score +0
Convergence, score=57.950929 
Run 7, Init, score 9.300501 
Run 7, Cycle 1, score +12.004003, flipped (9,2) 
Run 7, Cycle 2, score +9.915153, flipped (2,2) 
Run 7, Cycle 3, score +8.078770, flipped (5,1) 
Run 7, Cycle 4, score +8.844228, flipped (10,1) 
Run 7, Cycle 5, score +5.007560, flipped (3,3) 
Run 7, Cycle 6, score +4.800714, flipped (7,3) 
Run 7, Cycle 7, score +0
Run 7, Cycle 8, score +0
Run 7, Cycle 9, score +0
Convergence, score=57.950929 
Run 8, Init, score 11.779228 
Run 8, Cycle 1, score +12.060928, flipped (9,2) 
Run 8, Cycle 2, score +9.867867, flipped (4,2) 
Run 8, Cycle 3, score +6.384201, flipped (6,1) 
Run 8, Cycle 4, score +7.198101, flipped (5,1) 
Run 8, Cycle 5, score +5.517829, flipped (2,3) 
Run 8, Cycle 6, score +5.142775, flipped (10,3) 
Run 8, Cycle 7, score +0
Run 8, Cycle 8, score +0
Run 8, Cycle 9, score +0
Convergence, score=57.950929 
Run 9, Init, score 12.579849 
Run 9, Cycle 1, score +10.038786, flipped (1,2) 
Run 9, Cycle 2, score +9.164150, flipped (6,2) 
Run 9, Cycle 3, score +9.047549, flipped (10,2) 
Run 9, Cycle 4, score +6.885604, flipped (8,1) 
Run 9, Cycle 5, score +5.321847, flipped (2,3) 
Run 9, Cycle 6, score +4.913143, flipped (5,3) 
Run 9, Cycle 7, score +0
Run 9, Cycle 8, score +0
Run 9, Cycle 9, score +0
Convergence, score=57.950929 
Run 10, Init, score 15.666842 
Run 10, Cycle 1, score +9.991239, flipped (7,2) 
Run 10, Cycle 2, score +9.164150, flipped (6,2) 
Run 10, Cycle 3, score +9.073589, flipped (5,1) 
Run 10, Cycle 4, score +9.047549, flipped (10,2) 
Run 10, Cycle 5, score +5.007560, flipped (3,3) 
Run 10, Cycle 6, score +0
Run 10, Cycle 7, score +0
Run 10, Cycle 8, score +0
Run 10, Cycle 9, score +0
Convergence, score=57.950929 
Run 11, Init, score 20.338624 
Run 11, Cycle 1, score +9.991239, flipped (7,2) 
Run 11, Cycle 2, score +9.915153, flipped (2,2) 
Run 11, Cycle 3, score +7.397427, flipped (9,1) 
Run 11, Cycle 4, score +5.300925, flipped (6,3) 
Run 11, Cycle 5, score +5.007560, flipped (3,3) 
Run 11, Cycle 6, score +0
Run 11, Cycle 7, score +0
Run 11, Cycle 8, score +0
Run 11, Cycle 9, score +0
Convergence, score=57.950929 
Run 12, Init, score 25.808923 
Run 12, Cycle 1, score +7.145625, flipped (3,2) 
Run 12, Cycle 2, score +9.867867, flipped (4,2) 
Run 12, Cycle 3, score +5.388271, flipped (8,3) 
Run 12, Cycle 4, score +5.247423, flipped (1,3) 
Run 12, Cycle 5, score +4.492819, flipped (9,3) 
Run 12, Cycle 6, score +0
Run 12, Cycle 7, score +0
Run 12, Cycle 8, score +0
Run 12, Cycle 9, score +0
Convergence, score=57.950929 
Run 13, Init, score 20.467559 
Run 13, Cycle 1, score +10.038786, flipped (1,2) 
Run 13, Cycle 2, score +9.991239, flipped (7,2) 
Run 13, Cycle 3, score +7.785513, flipped (9,1) 
Run 13, Cycle 4, score +4.754688, flipped (10,3) 
Run 13, Cycle 5, score +4.913143, flipped (5,3) 
Run 13, Cycle 6, score +0
Run 13, Cycle 7, score +0
Run 13, Cycle 8, score +0
Run 13, Cycle 9, score +0
Convergence, score=57.950929 
Run 14, Init, score 17.986358 
Run 14, Cycle 1, score +9.056330, flipped (8,2) 
Run 14, Cycle 2, score +7.864961, flipped (4,1) 
Run 14, Cycle 3, score +7.635059, flipped (6,1) 
Run 14, Cycle 4, score +5.599947, flipped (2,3) 
Run 14, Cycle 5, score +5.007560, flipped (3,3) 
Run 14, Cycle 6, score +4.800714, flipped (7,3) 
Run 14, Cycle 7, score +0
Run 14, Cycle 8, score +0
Run 14, Cycle 9, score +0
Convergence, score=57.950929 
Run 15, Init, score 9.087699 
Run 15, Cycle 1, score +9.122293, flipped (3,2) 
Run 15, Cycle 2, score +9.056330, flipped (8,2) 
Run 15, Cycle 3, score +6.700256, flipped (10,1) 
Run 15, Cycle 4, score +8.716708, flipped (5,1) 
Run 15, Cycle 5, score +5.300925, flipped (6,3) 
Run 15, Cycle 6, score +5.247423, flipped (1,3) 
Run 15, Cycle 7, score +4.719295, flipped (4,3) 
Run 15, Cycle 8, score +0
Run 15, Cycle 9, score +0
Convergence, score=57.950929 
Run 16, Init, score 25.683173 
Run 16, Cycle 1, score +8.900375, flipped (5,1) 
Run 16, Cycle 2, score +8.854342, flipped (10,1) 
Run 16, Cycle 3, score +5.300925, flipped (6,3) 
Run 16, Cycle 4, score +4.719295, flipped (4,3) 
Run 16, Cycle 5, score +4.492819, flipped (9,3) 
Run 16, Cycle 6, score +0
Run 16, Cycle 7, score +0
Run 16, Cycle 8, score +0
Run 16, Cycle 9, score +0
Convergence, score=57.950929 
Run 17, Init, score 13.768203 
Run 17, Cycle 1, score +9.867867, flipped (4,2) 
Run 17, Cycle 2, score +9.604703, flipped (9,1) 
Run 17, Cycle 3, score +6.675910, flipped (10,1) 
Run 17, Cycle 4, score +7.353271, flipped (5,1) 
Run 17, Cycle 5, score +5.380049, flipped (8,3) 
Run 17, Cycle 6, score +5.300925, flipped (6,3) 
Run 17, Cycle 7, score +0
Run 17, Cycle 8, score +0
Run 17, Cycle 9, score +0
Convergence, score=57.950929 
Run 18, Init, score 16.703002 
Run 18, Cycle 1, score +5.592591, flipped (3,1) 
Run 18, Cycle 2, score +5.190525, flipped (7,1) 
Run 18, Cycle 3, score +7.287586, flipped (4,1) 
Run 18, Cycle 4, score +7.236623, flipped (10,1) 
Run 18, Cycle 5, score +5.304907, flipped (2,3) 
Run 18, Cycle 6, score +5.388271, flipped (8,3) 
Run 18, Cycle 7, score +5.247423, flipped (1,3) 
Run 18, Cycle 8, score +0
Run 18, Cycle 9, score +0
Convergence, score=57.950929 
Run 19, Init, score 19.156472 
Run 19, Cycle 1, score +10.600151, flipped (3,2) 
Run 19, Cycle 2, score +6.515134, flipped (2,1) 
Run 19, Cycle 3, score +6.904949, flipped (10,1) 
Run 19, Cycle 4, score +5.060365, flipped (6,3) 
Run 19, Cycle 5, score +4.913143, flipped (5,3) 
Run 19, Cycle 6, score +4.800714, flipped (7,3) 
Run 19, Cycle 7, score +0
Run 19, Cycle 8, score +0
Run 19, Cycle 9, score +0
Convergence, score=57.950929 
Run 20, Init, score 12.909265 
Run 20, Cycle 1, score +10.038786, flipped (1,2) 
Run 20, Cycle 2, score +5.600840, flipped (3,1) 
Run 20, Cycle 3, score +7.119270, flipped (8,1) 
Run 20, Cycle 4, score +7.734030, flipped (6,1) 
Run 20, Cycle 5, score +5.142775, flipped (10,3) 
Run 20, Cycle 6, score +4.913143, flipped (5,3) 
Run 20, Cycle 7, score +4.492819, flipped (9,3) 
Run 20, Cycle 8, score +0
Run 20, Cycle 9, score +0
Convergence, score=57.950929 
Final Score=57.950929

flips =

     0     0     0
     1     0     0
     0     1     0
     0     0     1
     0     0     0
     0     0     1
     0     0     0
     0     0     0
     0     0     0
     0     0     0

Flips =

     0     0     0
     1     0     0
     0     1     0
     0     0     1
     0     0     0
     0     0     1
     0     0     0
     0     0     0
     0     0     0
     0     0     0

The logical indices in position 1 contain a true value outside of the array bounds.

Error in obsinit>initpost (line 257)
                hmm.state(k).prior.Omega.Gam_rate(regressed,regressed) +  ...

Error in obsinit (line 22)
hmm = initpost(data.X,T,hmm,residuals,Gamma);

Error in hmmmar_init>run_initialization (line 92)
[hmm,residuals] = obsinit(data,T,hmm,options.Gamma);

Error in hmmmar_init (line 43)
        [Gamma{it},fehist{it}] = run_initialization(data,T,options,Sind,init_k(it));

Error in hmmmar (line 299)
                [GammaInit,fehistInit] = hmmmar_init(data,T,options,Sind);

Error in Examples (line 90)
    [hmm, Gamma, Xi, vpath] = hmmmar(X,T,options);
 
>>

**Comment by vidaurre** [comment]
Thanks so much for the very detailed report. I will look at it shortly. 
Best,
d

**Comment by vidaurre** [comment]
I have not been able to reproduce the error, I presume this was an issue with a previous version. I'm closing it, but i'm happy to look at it again.
