### ISSUE TITLE
Error about the function "getMaskedTransProbMats"

### ISSUE THREAD

**Issue by YingHe0** [OHBA-analysis/HMM-MAR#16]
When I used this function, Matlab reported this error:
    
> Undefined function or variable 'ind_ig'.

I checked this code:
> if order > 0
>             ind_ig = ind_ix(ind_ix>=t0+order+1);
>             ind_ig = ind_ig - n*order;
>         elseif length(embeddedlags) > 1
>             ind_ig = ind_ix((ind_ix>=t0+embeddedlags(1)+1) & (ind_ix<=t1-embeddedlags(end))  ); 
>             ind_ig = ind_ig - (n-1)*L - embeddedlags(1);
>         end

If "Order>0" and  "length(embeddedlags)>1" both are not  satisfied, the ind_ig won't be defined.  In my case, order = 0 and embeddedlags = 0, how to fix this problem?

**Comment by vidaurre** [comment]
I have fixed this now – thanks so much for reporting. 
d
