### ISSUE TITLE
Questions about the function "getMaskedTransProbMats"

### ISSUE THREAD

**Issue by YingHe0** [OHBA-analysis/HMM-MAR#18]
About this function:
        How to set the input "Masks" ? I can't understand the notes very well. 
>  A cell where each element is a vector containing the indexes (e.g. [1001:2000]) for which we wish to compute the LMTPM; indexes are with respect to the data (not the state time courses, which are
> typically shorter)
       The format of my data is a cell containing one (no. of time points X no. of channels) matrix per subject which included two groups. So If I want to compute the transition matrix of two groups, how to input the Masks?  Could you give me an example? Thank you very much!

**Comment by vidaurre** [comment]
I have made the documentation of the function a bit clearer now.
