### ISSUE TITLE
Mex Compiling in Windows

### ISSUE THREAD

**Issue by Markwelt** [OHBA-analysis/HMM-MAR#20]
Is there is a straightforward way to compile hidden_state_inference(_mx).cpp mex file on Windows?

Building it in mac and linux is well documented, but not on windows systems.  Tried contacting Giles Colclough but he is not academia anymore. Sorry to bother you for this trivial thing, but maybe you were asked already and have the solution at hand. I tried with working armadillo libraries (and openblas, arpack and lapack) but could not manage.

Thank you for your work and for your attention. 
Best

**Comment by vidaurre** [comment]
Hi Mark, 
unfortunately we have very little experience with Windows. We have either Mac or Linux here. So I'm sorry we cannot help. 
Is it too expensive to run in the non-MEX way? 
d

**Comment by Markwelt** [comment]
Yes, it takes a while for large datasets, the BIG options help a lot, but I think using the mex file is the real speed advantage.
Thank you for your reply. I'll try some more and I'll let people here know if I figure it out.

**Comment by vidaurre** [comment]
Hi Markwelt, I'm closing the Issue for now, let us know if you need more info or if you found how to solve it.
