### ISSUE TITLE
Results of the function "hmmpred"

### ISSUE THREAD

**Issue by dazzlingliu** [OHBA-analysis/HMM-MAR#21]
Hi Vidaurre,
I'm not very understand the results of this function "hmmpred". 
After running the code, I got "responseY" variable which **size is Timepoints*ndim**. Could I simply use the mean value of whole matrix to represent the predictive power on unseen data?
Besides, in my understanding, the predictive response should be **positive value**. The closer it is to zero, the worse the prediction. But **sometimes I got a lot of negative values in "responseY"**, and the mean value was also negative, which really confused me.
Thank you for your time.

This is the help information in function file:
function [responseY,responseR,Gamma] = hmmpred(X,T,hmm,Gamma,residuals,actstates,grouping)
%
% Predictive distribution of the response and error on potentially unseen data
% useful for cross-validation routines
%
% X     -----observations
% T     -----Number of time points for each time series
% hmm  -----hmm data structure
% Gamma  -----probability of current state cond. on data      
% residuals   -----in case we train on residuals, the value of those.
% actstates  -----Kx1 vector indicating which states were effectively used in the training, 
%                  -----The default is ones(K,1)
%
% responseY -----mean of the predictive response 
% responseR  -----mean of the predictive response for the residuals
% Gamma      -----estimated probability of current state cond. on data

**Comment by vidaurre** [comment]
Hi, 
Sorry for the confusion. This function returns the predicted signal, not the explained variance. This is useful for example to see how well an HMM-MAR (e.g. with an autoregressive model) fits the data. I have added a fourth output argument with the  explained variance. I also solved a problem within the function.
d
