### ISSUE TITLE
Sampling frequency?

### ISSUE THREAD

**Issue by LiFeng-NJU** [OHBA-analysis/HMM-MAR#24]
what does the Sampling frequency mean? the data's Sampling frequency  when it was recorded in the equipment? or the  time points calculated in the hmm_mar.FS =1 means the hmm got one point every time?Thank you so much

**Comment by vidaurre** [comment]
Hi, yes. The sampling rate is that of the data as it is presented to the algorithm. For example, if you have EEG data with 250 samples per second, then options.Fs = 250. If you have fMRI data with TR=2s, then  options.Fs = 0.5; 

Hope that helps
d

**Comment by LiFeng-NJU** [comment]
so thanks to you, hope you have a nice day~~
Can you tell me some details about Pistructure?Pistructure is a 1 by K vector,if i get 2 states then Pistructure can be [1,1]or[2,2]or[1,2], [1,1]means the result is start with state1, [1,2]means the result is start with state1(50%),state2[50%]?does i understand it correctly?

**Comment by vidaurre** [comment]
Hi, it should be zeros or ones, eg [0 1], [1 0], or [1 1].

Please refer to the wiki: "Pstructure and Pistructure: a more flexible way to restrict the possible pathways of state transitions. Pstructure is a K by K matrix with zeros or ones indicating which transitions are possible. Pistructure is a 1 by K vector of zeros and ones indicating with which states trials or sequences are allowed to start."
