### ISSUE TITLE
Pistructure

### ISSUE THREAD

**Issue by LiFeng-NJU** [OHBA-analysis/HMM-MAR#25]
so thanks to you, hope you have a nice day~~
Can you tell me some details about Pistructure?Pistructure is a 1 by K vector,if i get 2 states then Pistructure can be [1,1]or[2,2]or[1,2], [1,1]means the result is start with state1, [1,2]means the result is start with state1(50%),state2[50%]?does i understand it correctly?

**Comment by vidaurre** [comment]
Hi, it should be zeros or ones, eg [0 1], [1 0], or [1 1].

Please refer to the wiki:  "Pstructure and Pistructure: a more flexible way to restrict the possible pathways of state transitions. Pstructure is a K by K matrix with zeros or ones indicating which transitions are possible. Pistructure is a 1 by K vector of zeros and ones indicating with which states trials or sequences are allowed to start."
