### ISSUE TITLE
cleandata4hmm and comparison for clinical datasets

### ISSUE THREAD

**Issue by nooshinjava** [OHBA-analysis/HMM-MAR#26]

**Comment by vidaurre** [comment]
Hi,

I assume the issue is already solved? I guess one of your channels, in at least one of the data segments, is just a constant? 

Best,
d

**Comment by nooshinjava** [comment]
Hi,

Thanks a lot, I have found out the problem with some subjects in my
dataset.
Sorry for my impatience!
All the bests,
N
