### ISSUE TITLE
hmmmar crashed during initialisation - Stochastic learning

### ISSUE THREAD

**Issue by nathanecross** [OHBA-analysis/HMM-MAR#28]
I have been running hmmmar with stochastic inference, and it crashed at 
`Init: repetition 1, batch 24`
giving the following error message:
```
{^HIndex in position 1 exceeds array bounds.

Error in formautoregr (line 69)
                    X(t0+maxorder-o+1:t0+T(in)-o,:);

Error in setxx (line 40)
                XX =
                formautoregr(X,T,orders,hmm.train.maxorder,hmm.train.zeromean,0,B,V);

Error in evalfreeenergy (line 29)
    setxx; % build XX and get orders

Error in hmmsinit (line 341)
        loglik_init(i) = evalfreeenergy([],Ti,Gamma,Xi,hmm_init_i,Y,[],[0 1 0 0
        0]);

Error in hmmmar (line 188)
        [hmm,info] = hmmsinit(data,T,options);

```
This looks like it snagged an error with one of the subjects' data.. If so, is there a way to tell which subject it was running when the initialisation crashed?

**Comment by vidaurre** [comment]
Hi Nathan,

It seems that your specification of T is not matching the size of the data for one or more of your subjects. Could you try 

https://github.com/OHBA-analysis/HMM-MAR/blob/master/utils/internal/checkData.m

This should give you also an indication of which subject is the problem

d

**Comment by nathanecross** [comment]
Thanks for this check function! Unfortunately it didn't reveal any problems though...

Also, given my data is continuous (without trials), I have been setting T for each subject as the length of X:
```
for row = 1:numel(data)
    load(char(data(row,1)),'X')
    T{row,1} = length(X);
end
```

**Comment by vidaurre** [comment]
Problem was solved when updating the repository
