### ISSUE TITLE
Error: State time course inference returned NaN (out of precision).

### ISSUE THREAD

**Issue by accountdejuschu** [OHBA-analysis/HMM-MAR#29]
Hi!

Thank you for this very interesting toolbox.
When I tried to apply it to my MEG data set I get 1. a Warning and 2. an Error using hsinference (line 324): "State time course inference returned NaN (out of precision). There are probably extreme events in the data".
As you commented this issue should be treated within fb_Gamma_inference, but it seems not only my betas but also my alphas (which are then assigned as Gamma) seem to be full of NaNs...
My data has a Fs of 100Hz, 408 trials each 61 timepoints, 50 channels (after applying a PCA) and one binary feature.

Can you help me/ suggest what could be causing the problem? I'm also not really sure what this error/ warning really means - maybe you can also help me with that?

Thank you very much,
Juliane Schubert

**Comment by vidaurre** [comment]
Hi – thanks

Could you paste here the content of your 'options' struct, as well as the warning you are getting? 

If you are using a MAR that might the issue. It's too many channels. 

d

**Comment by accountdejuschu** [comment]
Hi thank you for the quick reply!

options = 

    classifier: 'LDA'
      CVmethod: 1
             K: 5
             c: [1×1 cvpartition]

The warning is the same as the error message.

**Comment by CameronHiggins** [comment]
Hi Julianne,

This problem can arise for a number of reasons, including the presence of extreme segments in the data (either segments with zero variance or with very high variance). It can also come about for other more technical reasons in the state inference that we would need to trace. I notice you are using the LDA classifiers, which are still somewhat under development - are you using the function tudatrain? Could you perhaps share the line you are using to call the toolbox?

Then, as a few rudimentary steps, could you try:
1. Normalise your data (in this case the PCs)
2. Check the data variance as a function of trials - see if some trials have much larger variance, and if so exclude them

If this doesn't resolve it, could you attach a small segment of data that replicates the error message and I will trace it on my computer? Many thanks,

Cameron

**Comment by vidaurre** [comment]
Hi  Julianne, I was wondering if we can close the Issue? 
Thanks

**Comment by accountdejuschu** [comment]
Hi,
I'm sorry somehow I got no notification of @CameronHiggins reply... And just saw it now! 
I was calling tucacv (since I have a binary classification problem).

Thanks for your suggestions I will check the data variance and see whether this solves the problem!

Many thanks

**Comment by accountdejuschu** [comment]
Hi,
yes it seems that the problem was that I had indeed some trials with extreme variance, after removing them everything seems to work fine now!

Thanks again for your quick help!
