### ISSUE TITLE
Applying HMM to epoched data

### ISSUE THREAD

**Issue by pauldhami** [OHBA-analysis/HMM-MAR#30]
Greetings,

Firstly, thank you for the wonderful toolbox. 

I have a naive question. I have EEG ERP data that is already epoched (and thus not continuous). From my understanding of the Quinn et al. 2018 Frontiers paper, no formal epoching was done:

"Crucially, the epoching was not applied to the MEG data used for the HMM inference, rather, the continuous MEG data is used without knowledge of the task structure or timings"

By question is can the HMM be applied to data this is epoched? Or would it be more appropriate to reclean the data as continuous and not epoch?

A second question is related to the embedded lags. For choosing the values here, is the primary thing to take into account the frequencies of interest? For example, in the context of epoched task data (with FS = 1000), if my ERP response of interest is 0 - 100 ms, this **doesn't mean** I should using an embedded lag of -100:100 to capture the ERP time? 

Any help would be greatly appreciated.
Thank you,
Paul

**Comment by vidaurre** [comment]
Hi Paul,

There's no fundamental problem with applying the HMM on epoched data. That's what we did in Vidaurre et al. 2019 (Cerebral Cortex) for example, and it worked fine. However, at the end of the day, that's imposing breaks in the data that they don't exist in reality. So perhaps it's a bit preferrable to have it as continuous data, if at all possible –but fine if you prefer not to do that.  

The second question: yes, the length of the embedded lag has to do with the frequencies you capture. 1000Hz is probably a too large sampling frequency, so you might consider downsampling. If you use -100:100: 

- First that's a lot of computational effort, so you could well do -100:10:100. 
- Second, the PCA parameter has something to say there as well (fewer PCs, more focus on low-frequency data). 
- Third, I guess you don't need a window that big anyway. At the end of the day, you want temporal resolution that tracks the cascade of activation during these 100-200ms, not one state that covers everything. 

Hope that makes sense. 
Diego

**Comment by pauldhami** [comment]
Dear Diego,

Thank you very much for your response. It is a big help!

Just to follow up on analyzing epoch data, I have just one condition, which I would then like to compare against the baseline to see how the stimuli modulates each of my K states.

I initially was going to export my data to FieldTrip to do this analysis, but came across hmmtest_epoched function which seems to do what I want.

I entered Gamma (as output by hmmmar).
With each trial having 2000 time points (Fs = 1000) and a total of 2295 trials across 30 subjects, I entered T as a 2295 array where each element is equal to 2000. 
Finally, I entered stimulus as a 2295 by 1 cell array, where each cell array contains a 2000 x 1 array, with all values of 0, except for the 1000th value which is equal to 1 (for the stimulus).

However, I am receiving the following error:

```
Error using sum
Invalid data type. First argument must be numeric or logical.

Error in mean (line 127)
        y = sum(x, dim, flag) ./ mysize(x,dim);

Error in zscore (line 54)
mu = mean(x,dim);

Error in hmmtest_epoched (line 65)
Y = zscore(Y);
```

I have two questions; any help would be greatly appreciated.

1. Are my inputs correct, or are the format of them causing the error?
2. Why is a zscore being applied to Y, the stimulus input?

Thank you again,
Paul

**Comment by vidaurre** [comment]
Hi,

I think the format must be causing the problem. The stimulus should be a (no. trials) x 1 vector, telling the class to which each trial or epoch belongs to (eg stimulus is a face or a motorbike). If I understood correctly, then your stimulus vector should be -1 for baseline or 1 for stimulus presentation. 

The z-score is just about centering the stimulus if it is a continuous variable, but it doesn't matter for your case. 

Visually, you can also look at the fractional occupancy (getFractionalOccupancy.m).  Quinn et al. 2019 does just that. 

Diego

**Comment by pauldhami** [comment]
Dear Diego,

Apologizes for bothering, but I am still having trouble with the stimulus variable.

There are a total of 2295 trials across 30 subjects. 

Each trial is the same (there was only 1 condition in this experiment and we would like to compare whether the stimuli modulates any of the K states). Each trial is epoched around the stimulus from -1 second to 0.999 seconds after at a Fs = 1000, meaning there are 2000 data points in each trial.

From your previous message, my stimulus should be 2295 x 1 vector. 

However, because all trials have the same condition, would my vector simply be a 2295 x 1 vector comprised of ones? I tried this, but the following lines of code on lines 65-66: 

```
Y = zscore(Y);
vY = sum(Y.^2);
```

makes the Y vector equal to 0, which leads to NaNs eventually later down in the code, and a p-value output of 0s. Accordingly, I must be doing something wrong.

Any help would be greatly appreciated.
Best,
Paul

**Comment by vidaurre** [comment]
No worries. 

That function only makes sense to compare two conditions. I thought you said that some trials corresponded to baseline. But if all trials are the same , then you can't test that way. 

This is similar to what we did in Vidaurre et al 2016 NeuroImage. There, we just showed the average fractional occupancy (like an ERP but for states). You can use the function getFractionalOccupancy.m for that. In that case, we did just that: to compare to "baseline trials" , as far as I remember.

d

**Comment by pauldhami** [comment]
Great, thank you so much Diego.
