### ISSUE TITLE
Error when using downsampling parameter

### ISSUE THREAD

**Issue by pauldhami** [OHBA-analysis/HMM-MAR#31]
Dear Diego,

So far, I have not been applying any downsampling to my data, which has a Fs = 1000.

After adding the options.downsample parameter to for example 250 or 100, I am running into the following error.

```
Error using zeros
Size inputs must be integers.
```

On line 45 of hmmsdecode.m

`Xi = zeros(downs_ratio * (sum(TT)-length(TT)*(L+1)),K,K,'single')`

The problem is from the output of (sum(TT)-length(TT)*(L+1).

I'm assuming using fix, floor, ceil, or round would cause issues down the line.

Any suggestions as how to solve this?

Thank you,
Paul

**Comment by vidaurre** [comment]
Apologies that this took some time. Fixed now
