### ISSUE TITLE
How to choose a proper K, and the explanation of results with different K values 

### ISSUE THREAD

**Issue by lsyoath** [OHBA-analysis/HMM-MAR#32]
Hi Diego,
Thanks for your explanation last time. There's a lot of things happened days before, and now we come back to our project. We finally decided to do HMM on our module-wise parcellation data.
Now I am confused about the k (number of state), cause I'm not sure how to choose a proper value. I saw someone said that EM algorithm can help on websites, but examples in HMM-MAR all give a certain value manually. So would you give me some guidance if it is possible ?

I'm looking forward to your replay. Thank you.

Best,
Siya

**Comment by vidaurre** [comment]
Hi Siya,

Common ways of selecting K is using the free energy, or the cross-validated likelihood ( cvhmmmar.m )

In my experience though, it's just different descriptions of the data with different levels of granularity. The important thing is that the conclusions you get hold across a reasonable range of K. 

Hope that helps. 

d
