### ISSUE TITLE
Consider a cloud CI service

### ISSUE THREAD

**Issue by acampbel** [OHBA-analysis/HMM-MAR#33]
Given public open source projects have free support for cloud ci services, consider leveraging one of them here. 🎉

https://blogs.mathworks.com/developer/2020/12/15/cloud-ci-services/

**Comment by nikosavola** [comment]
I suggest the scripts in the examples/ folder could be considered as integration tests with some example data, just to test that they run without errors.

The easiest free way to do this would be to use the [matlab-actions/setup-matlab](https://github.com/matlab-actions/setup-matlab) and [matlab-actions/run-tests](https://github.com/matlab-actions/run-tests) GitHub Actions.

**Comment by vidaurre** [comment]
Hi —thanks for your suggestions. 

In terms of data, we prefer to keep the package light. We do run some tests with test_script.m on synthetic data generated on the fly, but it might not be exhaustive. I'll look into those other tools

d

**Comment by nikosavola** [comment]
Ah, there are some tests already, in that case, I could try to implement some CI with the GitHub Actions.

These tests can then be expanded at some point to be more effective.
