### ISSUE TITLE
Error using hmmtestretest

### ISSUE THREAD

**Issue by ik362** [OHBA-analysis/HMM-MAR#36]
Dear Dr. Vidaurre,

Since updating the HMM-MAR toolbox as suggested I have encountered an error using the hmmtestretest function:

`Error using min`
`Invalid data type. The first argument must be numeric or logical.`

`Error in getGammaSimilarity (line 41)`
            `M(k1,k2) = M(k1,k2) + (T - sum(min(gamma1(:,k1), g(:,k2)))) / T / N;`

`Error in hmmtestretest (line 148)`
    `[~,assig, Gamma{irun}] = getGammaSimilarity (Gamma(1:irun-1), Gamma{irun});`

I don't understand why `gamma1(:,k1)` is not numeric. Any suggestions on how to solve this?

Thanks,
Isaac

**Comment by vidaurre** [comment]
Thanks for pointing this out. I've fixed it now. I'm closing the Issue but you can open it again if there's any problem.
