### ISSUE TITLE
Question around HMM Structure

### ISSUE THREAD

**Issue by raajc** [OHBA-analysis/HMM-MAR#37]
Thanks for the incredible toolbox. I had a quick question. Have you considered using a Hidden Semi-Markov model architecture where the future state not only depends on the current state, but also on the state previous? I'm curious about if it might reveal further insights about state-dependency in the brain - although I know that this would affect computational time and model complexity.

**Comment by vidaurre** [comment]
Thanks for the quesiton and sorry for the delay. 

We have looked into semi-markov models but they are much more expensive to run, and we found that, most often, the decomposition that we obtained were not very different from the standard HMMs. For that reason, we decided not to pursue it further. Of course, it might make difference in data sets other than the ones we tried, but we don't know that.

**Comment by raajc** [comment]
Thank you, that makes sense! I'll keep you updated if I find anything.
