### ISSUE TITLE
Minimum norm estimates

### ISSUE THREAD

**Issue by raajc** [OHBA-analysis/HMM-MAR#38]
Would you expect there to be any issues with applying the sign disambiguation method with data source localized using **minimum norm estimation** as opposed to beam-forming approaches mentioned in the documentation? Thank you!

**Comment by vidaurre** [comment]
We haven't tested this much to be honest, but I would say it's possible it has an impact. 

Note that the sign disambiguation method is not perfect anyways. It's a heuristic, and when you have a lot of channels, it's easy to get trapped in local minima.

**Comment by vidaurre** [comment]
I'm closing this now. Please reopen it if you have more comments
