### ISSUE TITLE
An issue with "simhmmmar" in example code

### ISSUE THREAD

**Issue by kekehia123** [OHBA-analysis/HMM-MAR#39]
Hi, 

I ran the example code, but ran into an error with the function "simhmmmar". Could you help me? Thank you very much!

Following is the code:

addpath(genpath('.')) % assuming we are in the HMM-MAR directory
K = 4; % number of states
ndim = 3; % number of channels
N = 10; % number of trials
Fs = 200;
T = 10000 * ones(N,1); % number of data points

hmmtrue = struct();
hmmtrue.K = K;
hmmtrue.state = struct();
hmmtrue.train.covtype = 'full';
hmmtrue.train.zeromean = 0;
hmmtrue.train.order = 0;

r0 = randn(ndim); % common factor
for k = 1:K
    hmmtrue.state(k).W.Mu_W = rand(1,ndim);
    r = randn(ndim);
    hmmtrue.state(k).Omega.Gam_rate = 1000 * (0.75 * r0' * r0 + 0.25 * r' * r + eye(ndim));
    hmmtrue.state(k).Omega.Gam_shape = 1000;
end

hmmtrue.P = rand(K) + 100 * eye(K);  
for j=1:K,
    hmmtrue.P(j,:) = hmmtrue.P(j,:) ./ sum(hmmtrue.P(j,:));
end;
hmmtrue.Pi = ones(1,K); %rand(1,K);
hmmtrue.Pi = hmmtrue.Pi./sum(hmmtrue.Pi);

[X,T,Gammatrue] = simhmmmar(T,hmmtrue,[]);

options = struct();
options.K = K; 
options.Fs = Fs; 
options.covtype = 'full';
options.order = 0;
options.DirichletDiag = 2; 
options.zeromean = 0;
options.verbose = 1;

[hmm, Gamma, Xi, vpath] = hmmmar(X,T,options);

The error message is:

Index exceeds the number of array elements (0).

Error in mvnrnd (line 35)
nsmp  = varargin{1};

Error in simgauss (line 34)
            X = X + repmat(Gamma(:,k),1,ndim) .* mvnrnd(mu,Cov);

Error in simhmmmar (line 97)
        Xin = [X0; simgauss(T(n),hmm,Gamma(t0:t1,:))];

Error in example (line 30)
[X,T,Gammatrue] = simhmmmar(T,hmmtrue,[]);

**Comment by vidaurre** [comment]
Hi, 

I can run this without problems. I think your repository must have been caught between versions somehow. If you git pull  the code now, it should work

d

**Comment by kekehia123** [comment]
> Hi,
> 
> I can run this without problems. I think your repository must have been caught between versions somehow. If you git pull the code now, it should work
> 
> d

Thanks a lot! I will try it.
