### ISSUE TITLE
An issue with how to obtain transition paobability 

### ISSUE THREAD

**Issue by YimengZeng** [OHBA-analysis/HMM-MAR#40]
Dear Dr. Vidaurre,

First, thank you very much for consistantly updating and sharing the HMM-MAR toolbox. I am currently trying to employ HMM model to analysis our data and found it both easy to use and efficient to compute. However, a issue with how to compute transition probability practically and theortically has confused me. Several questions listed below:

1. As function '**hmmmar.m**' requests input of 'T',  which, according to **wiki**, specifies the length of each segment (or trial or subject) of data. I am wondering what's the difference if I just assign total length of time points across session (trial) each subject?  Will the model be estimated separately for each segement (under the hypothesis that each session share the same state (mean, fc matrix) but however yields differences in other parameters (i.e. transition probility) ?   
2. A very interesting feature of HMM-MAR is that it can measure transition probability between sessions, as indicated by **getMaskedTransProbMats.m**. I am curious how conceptually this be done ? Does this require re-estimate the HMM model based on masks we give to it ? Or does this estimation related to structure 'T' which mentioned in Q1 ? (since it is natural to think that users might want to employ this function based on the 'T' structure they input to model, thus somehow overlapping with the input 'Masks' in the function conceputally) 
3. Finally, function **getTransProbs.m**  computes transition probability based on the most expressed state path. However, functions in getMaskedTransProbMats.m seems to estimate transition in a complicated way (by re-estimating some parameters ?). I am wondering if this difference may cause issues in determining which one is more suitable ?  For example, If the simple way **getTransProbs.m**  is good enough, then I could easily generalize the idea without need to understand mechanism underlying estimation.

Again, thanks for your effortful helpness!

Kindly regards,
Yimeng

**Comment by YimengZeng** [comment]
Additional issue,

I just run one hmmmar.m with data samples: 1226 timepoints *14ROIs * 25 subjects.
Core parameters set as:
stochastic_inference setting to 0
options.cyc = 1000; 
options.initcyc = 25;
options.initrep = 5; 
no.states =10;
repetitions =15;

Surprisingly,  the computing time is such small that it only last wtinin 5 minutes! I ran the same data using other HMM-based analysis and it cost me nearly 2 weeks.  My colleague ran the model independently before and also get astonishing speed . We are worried if we misrun the function or mis-set something. Just want to know before checking , does the HMM-MAR model can handle data under such amazing speed?

Best,
Yimeng

**Comment by vidaurre** [comment]
Hi Yimeng,

1. The only difference between just concatenating all sessions and keeping them as separate pieces is that the transition probability matrix does not apply between the end of one segment and the start of the next. There should not be a huge practical difference though, unless the "segments" are short. 
2. getMaskedTransProbMats.m just computes a transition prob matrix in subsets of the data. So there is no HMM re-estimation. Other than that, it's the same principle than the usual transition prob matrix, which is estimated from the entire data set. In all cases, we need T to know when each piece of data ends and starts the next. 
3. There's no difference: getTransProbs just gets the transition probability matrix that was computed from the original HMM, i.e. on the entire data set, without recomputing anything. Also, getTransProbs returns strictly the transition probabilities, apart from the self-transitions

**Comment by vidaurre** [comment]
PS: I responded to the stochastic learning question in a separate Issue

**Comment by YimengZeng** [comment]
It's a great pleasure to have your warmth reply! And your response indeed helps me a lot, as I am not very familiar with the step-by-step algorithm in HMM model (though I am working hard to learn it, lol). As for my research, I actually employed another HMM-based model called BSDS instead of the model in HMM-MAR toolbox. So maybe there still have some difference regarding to model hypothesis and estimation procedure. Anyway, it is great to know that HMM model in HMM-MAR toolbox cost much fewer time than I expect. Thanks again for your helpful response!
