### ISSUE TITLE
Estimation of number of states

### ISSUE THREAD

**Issue by dr-xenia** [OHBA-analysis/HMM-MAR#44]
Dear all,

I am looking forward to using the toolbox.

I have been wondering on how/whether you estimate the number of states? In the examples, there was always a fixed value for number of states. If it hasn’t been done so far, would you have an intuition on what would be the best method for the estimation?

Best wishes
Xenia

**Comment by vidaurre** [comment]
Hi Xenia, 

You could use either the free energy (7th output parameter of hmmmar.m); or some sort of test-retest reliability measure across half-splits of the data (if you have enough subjects). 

Our view is that the best way to go is to run the method for different number of states K, and see how results generalise across values of K and repetitions of the inference. In different words, there's rarely such thing as "the right number of states", so normally it is not worth to try to find a hard answer to that. 

d

**Comment by dr-xenia** [comment]
Thanks a lot!
