### ISSUE TITLE
Free Energy as model goodness of fit

### ISSUE THREAD

**Issue by ahhcj0716** [OHBA-analysis/HMM-MAR#47]
If I trained two models from two different datasets, and now there is new data, is free energy can be used to evaluate which model can be better at describing the new data?
And how to normalize the free energy if the data sample size is different.
Thanks!

**Comment by vidaurre** [comment]
Hi, 
The free energy, as it stands, essentially measures how a model suits a dataset, and it's typically used to compare two (usually nested) models on the same data set. I guess you can compute the free energy of each model on the new data set (so 2 models, 1 data set). 
Normalising the  the free energy to compare between 2 different data sets is at best a heuristic, and I wouldn't be sure what's the principle behind it
Thanks.
d
