### ISSUE TITLE
How to get stable results with a certain K

### ISSUE THREAD

**Issue by lsyoath** [OHBA-analysis/HMM-MAR#49]
Hi,
I've done repetitions of HMM with one K value, but found that each time, the TPM, FO matrix and activation maps showed different pattern.  So I was confused. Is this how it should be ? Or it indicates that the K value is not suitable?
Thank you for replying.  

Best, Siya

**Comment by vidaurre** [comment]
Hi Siya,

The HMM is subject to an estimation process that starts randomly and can fall in local minima, just like ICA and many other models. That will become more acute the more complex is your model (higher K, larger number of parameters, etc) and the more noisy and limited is your data. Please have a look here for some discussion on this.

Also please note that the order of the states is completely random anyway, so the first state in one run can correspond to the third state in another run, for example. For the transition probability matrices to be comparable you need to reorder the states. I might write a function to do this soon, but in the meantime you can use getGammaSimilarity.m

Thanks
d
