### ISSUE TITLE
When analyzing eeg data, do I need fsl and osl software? Such as seeg data?

### ISSUE THREAD

**Issue by zbjbiubiubiu** [OHBA-analysis/HMM-MAR#51]
Hi,
     I read your FAQ mentioned that when analysis M/EEG data ,a good point to start is Quinn et al. (2018). The article mentioned "the preprocessing and source-space parcellation analyses are performed using the OHBA Software Library (OSL1). This builds upon Fieldtrip, SPM and FSL to provide a range of useful tools for M/EEG analyses".
     I want to know whether FLS and QLS are also needed when analyzing SEEG data. 
     Thanks for your attention. I'm looking forward to your reply.

**Comment by vidaurre** [comment]
No need for this software. It's stand-alone, unless you want to work with SPM objects
