### ISSUE TITLE
getMaskedTransProbMats error - Omega

### ISSUE THREAD

**Issue by pauldhami** [OHBA-analysis/HMM-MAR#56]
Dear Diego, 

I am interested in comparing the transition probability matrices between two groups.

Accordingly, I am trying to use the **getMaskedTransProbMats** function.

I have a few questions pertaining to my use of the function.

1) Can X (the data) be the same cell data that is initially used with hmmmar? Or must it be in a matrix format with all the data from all participants collapsed?

2) After setting up X and Masks in a way I believe is correct, I am running into the error below. It appears to be looking for the field of Omega in hmm.prior, which is not there after my initial call to hmmmar.  

Any help with this would be greatly appreciated.

Thank you.
Paul

```
>> [P_MDD,Pi_MDD] = getMaskedTransProbMats(source_data_flipped,T,hmm,Masks_MDD,Gamma,Xi);
Warning: Both BIGNinit and BIGNinitbatch were specified. Ignoring BIGNinitbatch 
> In checkoptions (line 115)
In hmmmar (line 92)
In getMaskedTransProbMats (line 45) 
Starting parallel pool (parpool) using the 'local' profile ...
Connected to the parallel pool (number of workers: 8).
Unrecognized field name "Omega".

Error in hmmsinith (line 49)
        if isfield(hmm,'prior'), Omega_prior = hmm.prior.Omega; hmm = rmfield(hmm,'prior'); end

Error in hmmmar (line 194)
        [hmm,info] = hmmsinith(data,T,options,hmm);

Error in getMaskedTransProbMats (line 45)
    [hmm, Gamma, Xi] = hmmmar (data,T,options);
 
```

**Comment by vidaurre** [comment]
Hi Paul, 

To your first question, X can be the same format than when you called the hmmmar.
I wonder if you are using an old version of the code, though. You should not be getting into line 45 (where the error jumps) if you are specifying the parameters Gamma and Xi. 

Also, I could run the following toy code with no problem:

X = randn(2000,5); T = [1000 1000];
for j = 1:5, X(:,j) = smooth(X(:,j),100); end
options = struct();
options.K = 2; 
[hmm, Gamma, Xi] = hmmmar(X,T,options);
M = {[1:1000],[1001:2000]};
%%
[P_MDD,Pi_MDD] = getMaskedTransProbMats(X,T,hmm,M,Gamma,Xi);
[P_MDD,Pi_MDD] = getMaskedTransProbMats([],T,hmm,M,Gamma,Xi);
[P_MDD,Pi_MDD] = getMaskedTransProbMats(X,T,hmm,M);

**Comment by vidaurre** [comment]
I'm closing this as it seems solved

**Comment by pauldhami** [comment]
Hi Diego,

Sorry to bump an old issue, but I am still running into the same issue.

I think it has to do with Xi being an empty vector due to the use of stochastic methods?
