### ISSUE TITLE
HMM Features for two datasets

### ISSUE THREAD

**Issue by pauldhami** [OHBA-analysis/HMM-MAR#57]
Dear Diego,

I am working on a dataset with 100 healthy participants and 100 healthy clinical patients. I am ultimately interested in using the HMM features provided by your toolbox on an external dataset to assess whether the HMM features can predict group classification with good performance. 

I wanted to ask how about one could do this within the HMM framework (or if it is even possible). My first instinct was to run the HMM using all available participants (including those of the external validation dataset), build the classifier using the original 200 participants, and then extract the data of those participants belonging to the validation set. Would this be an appropriate approach. My confusion comes as to whether the HMM should be run once with all participants, or two separate times (one with the original 200 participants), and the other with the external dataset only.

Any thoughts on this would be greatly appreciated.
Paul

**Comment by vidaurre** [comment]
Hi,

This is not an HMM question, but a more general one. I know others disagree, but my opinion is that it is fine to run the HMM on all participants as far as you don't use the labels. Some will say that's not kosher, but it depends on the application. In your particular case, where the aim is interpretation (it would be different in BCI), I think this is fine. 

We were following a similar approach here : https://www.sciencedirect.com/science/article/pii/S1053811920311988 , and we ended up putting the HMM estimation within a CV loop as well at the request of a reviewer, and it didn't make a lot of a change.

d

**Comment by pauldhami** [comment]
Thank you very much Diego.

I'm assuming if I have two separate conditions that aren't in the same session that I want to compare (e.g., resting state during fixation, and resting state during movie watching), then both should be included in the single HMM model?

**Comment by vidaurre** [comment]
Hi Paul, 
I would say the simplest is to include all of them in the same model, so that states correspond later on for all subjects (ie state 1 is state 1 for everyone). Then you can test on fractional occupancies. Or "dual estimate" at the subject level and test other parameters (Vidaurre et al., 2021; NeuroImage). 
You can also run it for each group separately, but then it might a bit trickier to know how the states correspond between runs (trickier but possible).
Hope that helps
d

**Comment by vidaurre** [comment]
Hi Paul, I'm going to close this. Let us know if you have any other quesiton
