### ISSUE TITLE
Sparse prior on set of nodes and frequencies of each state

### ISSUE THREAD

**Issue by davidhaslacher** [OHBA-analysis/HMM-MAR#58]
Dear Diego,

In the HMM-MAR you included automatic relevance determination priors on the autoregression coefficients to ensure that each state manifests itself in a sparse set of nodes and frequencies. In contrast, the HMM-TDE formulation contains a Gaussian emission distribution over time-delay embeddings. Did you implement any mechanism to ensure a sparse set of nodes and frequencies for each state? I'm working on a Python implementation of HMM-TDE, and would like to stick as closely as possible to your model. Thanks for any feedback!

Best,

David

**Comment by vidaurre** [comment]
Hi David, 
In the TDE model the states are defined by (auto/cross-) covariance matrices (ie across channels and time points). In that case, the regularisation comes from the prior as well: each covariance matrix is distributed Wishart and there is a Wishart distributed prior distribution. In the MAR model the prior is applied on the autoregression coefficients, which are Gaussian-dsitributed. People call ARD to the latter case only (Gaussian), but it's all the same idea. Except there's no sparsity for the Wishart, just a regularisation pushing the estimation towards a diagonal matrix. 
Hope that helps
d

**Comment by vidaurre** [comment]
Hi David, I'm going to close this, let us know if you have any other questions
