### ISSUE TITLE
run_TUDA.m problem

### ISSUE THREAD

**Issue by LiFeng-NJU** [OHBA-analysis/HMM-MAR#59]
Dear Diego,
  the TUDA Module maybe have some problem, when I try to run the run_TUDA.m file, it got the run error. the Chinese mean： wrong usage .*, Matrix dimensions must agree. 
![image](https://user-images.githubusercontent.com/27933069/137697098-167264fc-06a7-4c76-bcc0-2f1e2bd34eba.png)

**Comment by LiFeng-NJU** [comment]
This situation also happened on my data set, so I had to go back to the HMM-MAR-logistic version, but the homepage told me to update to the latest version, so I am embarrassed now, thank you very much for your help.

**Comment by vidaurre** [comment]
Hi, we will have a look. Just to make sure: do you have the latest version of the toolbox?

**Comment by LiFeng-NJU** [comment]
> 你好，我们去看看。只是为了确保：您是否拥有最新版本的工具箱？

Sure ， I got the latest version of the toolbox. Thanks for your reply~

**Comment by vidaurre** [comment]
Issue solved?
