### ISSUE TITLE
spectbands.m

### ISSUE THREAD

**Issue by saltwater-tensor** [OHBA-analysis/HMM-MAR#61]
Hi Diego,
In the function spectbands.m wherever the Matlab function sum is being used it is important to specify the dimension across which to sum. 
The function runs into trouble if the variable "ind" has only one entry. Then the Matlab sum function starts summing across the spatial dimension i.e. the first non-singleton dimension it encounters. 
So instead of : sum(sp_fit.state(k).psd(ind,:,:)) it should be sum(sp_fit.state(k).psd(ind,:,:),1)

Cheers.

**Comment by vidaurre** [comment]
Thanks a lot for pointing this out. I've just corrected it.
Best
d
