### ISSUE TITLE
HMM-MAR model for EEG data

### ISSUE THREAD

**Issue by he-ling5** [OHBA-analysis/HMM-MAR#62]
Hi Dr. Vidaurre,

Thank you for the wonderful toolbox. I am studying the code these days and looking forward to using the toolbox. But I'm confused about some questions.

Currently, I am working on the detection of epilepsy by using EEG signals. and I would like to know whether your code can achieve this purpose.

And I ran code hmmmar. m, which trains the HMM model, right? But for my test set which code should be used to test, so as to achieve the prediction of epilepsy.

Any help would be greatly appreciated.
Thank you,

He

**Comment by vidaurre** [comment]
Hi, 

The toolbox can definitely be used for EEG, but I am not sure of exactly the goal of the analysis. Coudl you be more specific? 

Also, did you have a look at the Wiki? There's a lot of informaiton there. So that might be useful.

d
