### ISSUE TITLE
Small bug in fb_Gamma_inference.m

### ISSUE THREAD

**Issue by jnvandermeer** [OHBA-analysis/HMM-MAR#64]
I think the hidden_state_inference_mx.mexa64 function is not called with the proper amount of arguments.
Causing it to say: 'Something strange happened in the initialisation' in  (hmmmar_init.m).

I am on Linux, red hat Maipo.

On line 1, in function hidden_state_inference_mx.m:
function [gamma, Xi] = hidden_state_inference_mx(B, Pi_0, P, order)

And in fb_Gamma_inference.m, it's also called with 2 arguments - I think this is the key thing where things go wrong.

In hidden_state_inference_mx.cpp, there will be errors raised if less than 3 outputs are provided.

I think in an older version of the HMM_MAR, the hidden_state_inference_mx was called not in fb_Gamma_inference, but in hsinference.m, with 3 arguments - and there it runs fine. I should probably update that version of HMM-MAR though!

Thanks
Johan

**Comment by vidaurre** [comment]
Hi Johan,
As you say, it must return 3 output parameters or it might complain depending on the platform. 
I don't maintain the MEX part so I wasn't aware, but I have corrected it now on fb_Gamma_inference.m
Many thanks for pointing this out.
d
