### ISSUE TITLE
Issues with the input dimensions of the data

### ISSUE THREAD

**Issue by ghost** [OHBA-analysis/HMM-MAR#67]
Dear Dr. Vidaurre:
Thank you for the wonderful toolbox. I am studying the code these days and looking forward to using the toolbox. 

This was my first time to study EEG signal processing by HMM, and after looking at WIKI, I tried to run the code in example.The first time MATLAB reported an error, I added the statement: "hmmtrue.train.lowrank = 0;". It worked fine. Then I tried to understand the code, but I still didn't understand much after two weeks. I was confused and a little frustrated.

Could you please provide some suggestions on how to learn this Toolbox?
Any help would be greatly appreciated.

Yifan

**Comment by vidaurre** [comment]
Hi, 

Could you specify in which file you got the error? I will have a look.

The toolbox has grown to have a lot possibilities, so that unavoidably means that the code itself is relatively complex.  I wouldn't recommend reading the code directly unless you want to work on it as a developer. Apart from the Wiki, A tutorial-like paper that might be useful is [Quinn et al., 2018](https://internal-journal.frontiersin.org/articles/10.3389/fnins.2018.00603/full). It includes aspects of preprocessing that might not be pertinent to you, and it focuses on MEG —but should also apply to EEG for the most part (except perhaps the source reconstruction part).

What kind of analysis would you like to do anyway? What parts of the Wiki are unclear to you, given your purposes? 

Thanks
d

**Comment by ghost** [comment]
Hi Vidaurre,
Thanks for your reply. I will try to read the  paper you mentioned for further study.

My purpose is to use HMM to identify the state of EEG in Parkinson patients and understand the corresponding features under different states, such as spectrum.

And I run the code in [Examples](https://github.com/OHBA-analysis/HMM-MAR/wiki/Examples), 
the error is : reference to non-existent field 'lowrank',  traced back to "p = hmm.train.lowrank; do_HMM_pca = (p > 0);" in the function getFuncConn().  
So it didn't work well in "subplot(2,4,1), imagesc(getFuncConn(hmmtrue,1)), colormap('gray'), set(gca, 'Title', text('String', 'Simulated covariance: state 1'));"  I can't get figure about the covariance.
Therefore, I add "hmmtrue.train.lowrank = 0;"

Maybe my problem is that I don't figure out the relationship between several structures and the training process：
hmmtrue (HMM-MAR structure, with Gaussian observations)
hmm (get from funtion hmmmar() )
options (HMM model with Gaussian states)
options (HMM-MAR model, even when the data was generated with a HMM-Gaussian) 

Also, thanks for your advice, I think it's really not necessary to read every line of code directly.

**Comment by ghost** [comment]
Hi Dr. Vidaurre,
  I have been having some problems with the toolbox recently and would like your advice.
  I ran the example provided by the toolbox named [run_HMMMAR.m](https://github.com/OHBA-analysis/HMM-MAR/blob/master/examples/run_HMMMAR.m). The data input and some parameter settings are as follows:

full_data = load('D:\University\Medical Signal Processing\data\data_13subjects.mat');
full_data = struct2cell(full_data);

sub1_bc = cell2mat(full_data{1}{1}(2))'; % best channel of left side L2L3
sub2_bc = cell2mat(full_data{1}{2}(2))'; % best channel of left side L2L3
s1_1 = sub1_bc(1:30105); %subject1
s1_2 = sub1_bc(30106:81977);
s1_3 = sub1_bc(81978:105184);
s1_4 = sub1_bc(105185:127561);
s1_5 = sub1_bc(127562:164445);
s1_6 = sub1_bc(164446:174142);
s1_7 = sub1_bc(174143:228618);
s1_8 = sub1_bc(228619:280841);
s1_9 = sub1_bc(280842:336683);
s2_1 = sub1_bc(1:49702); %subject2
s2_2 = sub1_bc(49703:90249);
s2_3 = sub1_bc(90250:154427);
s2_4 = sub1_bc(154428:202371);
s2_5 = sub1_bc(202372:266525);
data = {sub1_bc sub2_bc};

L1_1 = length(s1_1);
L1_2 = length(s1_2);
L1_3 = length(s1_3);
L1_4 = length(s1_4);
L1_5 = length(s1_5);
L1_6 = length(s1_6);
L1_7 = length(s1_7);
L1_8 = length(s1_8);
L1_9 = length(s1_9);
L2_1 = length(s2_1);
L2_2 = length(s2_2);
L2_3 = length(s2_3);
L2_4 = length(s2_4);
L2_5 = length(s2_5);
T = {[L1_1 L1_2 L1_3 L1_4 L1_5 L1_6 L1_7 L1_8 L1_9],[L2_1 L2_2 L2_3 L2_4 L2_5]};

data_modality = 'LFP' ; % one of: 'fMRI', 'M/EEG', 'M/EEG power' or 'LFP' 
no_states = 6; % the number of states depends a lot on the question at hand
Hz = 1; % the frequency of the data
stochastic_inference = 0; % set to 1 if a normal run is too computationally expensive (memory or time)
N = length(T); % number of subjects

Nothing else in the file has changed.
When I only use data from one of the two subjects, the program runs without error but the resulting state time courses does not change, the result are horizontal lines (Gamma and vpath). 
When I use data from two subjects at the same time, like the code pasted above, the program runs with an error:
Incorrect use of CAT
The dimensions of the arrays to concatenate are inconsistent.

error cell2mat (line 75)
            m{n} = cat(2,c{n,:});
error hmmspectramar (line 143)
            data = cell2mat(data);
error run_HMMMAR (line 164)
    spectra = hmmspectramar(data,T,[],Gamma,options_spectra);

I want to know whether the data size of multiple subjects in LFP format should be the same, and whether the length of each session should be the same.

Looking forward to your reply.
Xu

**Comment by vidaurre** [comment]
Hi, sorry for the delay in answering. 

About the error in Examples, I've just fixed it. 
In there, hmmtrue is the ground-truth generating model, and hmm the estimation (which setup is made in options).

About your problem in the second message, there seem to be different issues. There's definitely something wrong if your Gamma and vpath are horizontal lines. There's probably NaNs somewhere. 

So if I understand correctly, you have one single channel, correct? It seems your run for one subject doesn't work since your Gamma and vpath  are not correct. What if you just run it in one segment, say sub1_bc(1:30105)? This should be T x 1. 

The error in hmmspectramar appears to be a problem of the dimensions in the data. I wonder if that is not causing the other problem too

d

**Comment by Ivan-Xu1874** [comment]
Hi Vidaurre,

    Thanks for your reply！
    As for the problem Gamma and vpath are horizontal lines, I take your advice and try again, solve the problem of data input dimensions. I change some parameters and plot all timepoints, and I can see the change between different states but not very often. If I write my own code using the functions provided by the toolbox, the frequency of state changes is more obvious. I think it might be a parameter setting problem.
    Besides, I have a new problem when I use a function to plot the spectrum(hmmspectramt and hmmspectramar), the two axes are in the wrong position, they are exactly opposite. That is to say, the curve is correct, but the X-axis values are plotted vertically and the Y-axis values are plotted horizontally. I think it is probably a problem inside the function, and I wonder if there is a way to solve the problem.
    Any help would be greatly appreciated.

Xu

**Comment by Ivan-Xu1874** [comment]
Hi Vidaurre，
    Thanks for your suggestions. Now, I have solved the problem of data dimension, get the HMM states and use the function (hmmspectramt()) to get spectrum of different state. 

    Then I try to use the function to make band decomposition (spectbands()), and this function result in a stuct with the spectral information across bands, and I just want to know whether the maximum value in the PSD matrix coefficient represents the state belongs to this band ?

    Besides, I want to use the HMM to compare the data with different condition, such as changes in state and spectrum before and after certain stimulus.  If the data under the two conditions are separated for HMM training, the results have randomness (curves with the same color may represent different states). If the data are trained together, then segment the data from the corresponding time points(For example, 1-2000 is before stimulation, and 2000-4000 is after stimulation) in Gamma for subsequent spectral observation, is it reasonable?

    Hoping for your reply.

**Comment by ghost** [comment]
Hi Vidaurre，

    Thanks for your suggestions. Now, I have solved the problem of data dimension, get the HMM states and use the function (hmmspectramt()) to get spectrum of different state.

    Then I try to use the function to make band decomposition (spectbands()), and this function result in a stuct with the spectral information across bands, and I just want to know whether the maximum value in the PSD matrix coefficient represents the state belongs to this band ?

    Besides, I want to use the HMM to compare the data with different condition, such as changes in state and spectrum before and after certain stimulus.  If the data under the two conditions are separated for HMM training, the results have randomness (curves with the same color may represent different states). If the data are trained together, then segment the data from the corresponding time points(For example, 1-2000 is before stimulation, and 2000-4000 is after stimulation) in Gamma for subsequent spectral observation, is it reasonable?

    Hoping for your reply.

**Comment by vidaurre** [comment]
Hi,
This seems to be a different issue than the one that the original thread. 
Could you please create a new Issue with it? Thanks
d
