### ISSUE TITLE
Stochastic state knock out

### ISSUE THREAD

**Issue by RomeshA** [OHBA-analysis/HMM-MAR#7]
Attached is input for `hmmmar`
 
```
hmmmar(V,t,options)
```

The input corresponds to 5 channels, 10 subjects, 400 samples per subject, 3 actual states. When run, for each of the initialisations (single subject) it switches off 5 states i.e. it correctly infers the 3 states. However, in the final run, all 8 states are still present in the output. If stochastic is disabled (e.g. `options.BIGNbatch=10`) then it also correctly gets the 3 states. 

Expected behaviour is that the stochastic run also knocks out the states

[debug.mat.zip](https://github.com/OHBA-analysis/HMM-MAR/files/668445/debug.mat.zip)

**Comment by vidaurre** [comment]
options.dropstates = 0 is now the default and mandatory option for stochastic inference.
