### ISSUE TITLE
Possible bug in updateW

### ISSUE THREAD

**Issue by saltwater-tensor** [OHBA-analysis/HMM-MAR#71]
Hi Diego,
Matlab produces the following bug while running the M step of the HMM.
I think the hmm.state(k).W.S_W(validentries,validentries) matrix should be set back to being full and this error should be resolved.
Please check.

Cheers.

Error using  * 
MTIMES (*) is not supported for one sparse argument and one single argument.
Error in updateW (line 247)
            muW = hmm.state(k).W.S_W(validentries,validentries)*temp(:);
Error in obsupdate (line 34)
            [hmm,XW] = updateW(hmm,Gamma,residuals,XX,XXGXX,Tfactor);
Error in hmmtrain (line 161)
        hmm = obsupdate(T,Gamma,hmm,residuals,XX,XXGXX);
Error in hmmmar (line 434)
            [hmm0,Gamma0,Xi0,fehist0] = hmmtrain(data,T,hmm0,GammaInit,residuals_wr,fehistInit);

**Comment by vidaurre** [comment]
Hi —thanks for reporting, we are looking into it. 

That bit of code is specific to an experimental model Cameron Higgins has been working on, and you shouldn't be getting there in a standard run. Could you let us know what configuration of options did you use to trigger that error? 

Many thanks
d

**Comment by saltwater-tensor** [comment]
Default TUDA options

**Comment by vidaurre** [comment]
We could not replicate the error (run_TUDA for example runs fine).
We believe it's a version incompatibility.
