### ISSUE TITLE
MTIMES (*) is not supported for one sparse argument and one single argument (Please check the entire repo for this error)

### ISSUE THREAD

**Issue by saltwater-tensor** [OHBA-analysis/HMM-MAR#72]
Hi Diego,
Matlab produces the same error here:

Error using  * 
MTIMES (*) is not supported for one sparse argument and one single
argument.
Error in evalfreeenergy (line 408)
                                tmp = (XX(:,Sind(:,n1)) *
                                hs.W.S_W(index1,:));
Error in hmmtrain (line 109)
            fehist(end+1) =
            sum(evalfreeenergy(data.X,T,Gamma,Xi,hmm,residuals,XX));
            Error in hmmmar (line 434)
            [hmm0,Gamma0,Xi0,fehist0] =
            hmmtrain(data,T,hmm0,GammaInit,residuals_wr,fehistInit);

**Comment by vidaurre** [comment]
Hi, 

As in your previous Issue, that should not be a problem normally (you shouldn't have sparse matrices in a normal run). Could you specify the options you are using, and how you are calling the code? 

Many thanks
d

**Comment by saltwater-tensor** [comment]
Default TUDA options

**Comment by vidaurre** [comment]
Hi, could  you paste here the contents of options? 
Thanks
