### ISSUE TITLE
Activating "dropstates" in stochastic learning

### ISSUE THREAD

**Issue by mkh1989** [OHBA-analysis/HMM-MAR#74]
Dear Dr. Vidaurre,

How can I activate "options.dropstates" when I work with stochastic learning?

When I look at the fractional occupancy (FO) of each state, there is one (sometimes two and three) state with zero FO. By looking at the data, the activeness of this state corresponds to noise in the data. For further analysis, this state should be removed. Is there any solution for this?

Thank you in advance,
MKH

**Comment by vidaurre** [comment]
Hi —thanks

Actually that option does not exist in the current implementation; it could be done theoretically, but it just makes the code more complicated, so we decided it's just easier to ignore the states with ~0 FO in subsequent analyses. 

I have added the function hmmprune.m, which you can call after the inference to remove unused states more easily: 

[hmmpruned,Gammapruned,Xipruned] = hmmprune(hmm,Gamma,Xi);
  or
[hmmpruned,Gammapruned] = hmmprune(hmm,Gamma);

d
