### ISSUE TITLE
Permutation test for between-state comparisons

### ISSUE THREAD

**Issue by mkh1989** [OHBA-analysis/HMM-MAR#75]
Dear Dr. Vidaurre,

As far as I know, in the "specttest.m" function, there is an option for between-state comparisons which performs a permutation test by permuting the variable of interest only among the states. Given that the number of states is not large (e.g. 4, 8, 12, etc), the number of all possible permutations is much less than the number of permutations for the test (e.g. Nperms = 5000 or 1000). In this case, among 5000 repetitions there are some values repeated many many times. 

If I am right and this is an issue, do you have any suggestions to deal with this?

Thank you in advance,
mkh

**Comment by vidaurre** [comment]
Hi, 
You are right, if the number of states is too low there won't be enough distinct permutations. However, for K=8, this is already 8! = 40320, which is a sufficient number (for K=6 it would be too low though). I'm afraid there's not an obvious workaround, except to increase K.
Thanks
d
