### ISSUE TITLE
Question about HMM spectrum and hmmtest()

### ISSUE THREAD

**Issue by ghost** [OHBA-analysis/HMM-MAR#76]
Hi Dr. Vidaurre,

   Recently, I have some questions when I use the toobox.

1. I'm confused about the function hmmspectramar() and hmmspectramt(), I use the same data for HMM and the results(curves)are a little different, I wonder how to choose the two functions? Do they have any requirements or limitations on the data?
2. I want to use the hmmtest() to do some statistical testing, for example, I use one subject's LFP data(continueous,Fs = 250) ,the data is marked by three conditions, I divide the data to 11 trials T = [L1 L2 L3...L11], Tsubject = length(data), Y = [100;100;100;010;010;010;010;001;001;001;001]. but I get an error, and I find a problem here:

if ~isfield(hmm.train,'downsample') || ~isfield(hmm.train,'Fs')
    r = 1; 
else
    r = hmm.train.downsample/hmm.train.Fs;
end

I don't use downsample, but it always jumps to the else statementr to calculate r,and r is always zero which results in T, Tsubject and TperSubj being zero.I feel a little strange, is there something wrong with the way I use it, like the input format?

Hoping for your reply.

**Comment by vidaurre** [comment]
Hi 

1. The estimation (multitaper and autoregressive fitting) methods are by construction quite different, so it's expected that the curves will be a little different. For example, if the AR order is low, then it will be limited in how many peaks it can find. Additionally, if the state switching is too fast, this can leak into the multitaper estimation, which doesn't happen for hmmspectramar(). I would recommend to get a spectral estimation over the entire data, using for example pwelch, and compare with the results of  hmmspectramar() and hmmspectramt() .
2. I see there is a problem in there. I have corrected it and it should be fine now. Thanks for reporting. 

Hope that fixes the problem, I will leave the Issue open for a few days in case you want to comment.

Best,
d

**Comment by ghost** [comment]
Hi,

    Thanks for fixing the code, the problem was solved. In addition, I still have some questions about hmmtest()，I'd like to know  if I get a big p value (maybe larger than 0.5), does that mean there's no significant difference under different conditions.

    Besides, I have some problems in the input of hmmtest():
    Now I have the data of 9 subjects, each subject has one channel, and the data of each subject is divided into 3 conditions(totally 27 segments). I want to see if there is a significant difference in their FO or other results under different conditions. 
    I concatenate all the data into a vector(sub1_1,sub1_2,sub1_3, sub2_1,sub2_2...), T is a vector of data length for each segment as[L1, L2,...,L27] and Tsubject is a vector of data length for each subject as[L1, L2,...,L9], Y dimension is 27×3 (trials×conditions). This input mode will report an error 'Y must have as many rows as subjects'. Since there are not enough trials for each subject, I find only grouplevel can be tested, so I try other inputs and it is feasible to use one subject's data input as originally described in Question 2. 

    So I wonder how to understand the grouplevel here and if I want to use the all data group by condition, could you give some advice on the data input?

    Thank you again and look forward to your reply.

**Comment by Ivan-Xu1874** [comment]
Hi Diego，
    In addition, I have a quick question about the amount of data. I run the HMM using only one channel per subject at a time(about 5 min and the samplingrate is 1000Hz). Although the spectrum observed by other means(such as FFT) contains a wide range of frequencies, but there is no definite peak in the spectrum of each state obtained using hmmspectmar() or hmmspectmt(). Compared with the papers in wiki, my data amount is too small, I tried a lot of settings about 'options', but the result is still not good, is that the reason?

**Comment by Ivan-Xu1874** [comment]
Here's an example, the spectrum of each state is very similar
<img width="418" alt="spec_mt" src="https://user-images.githubusercontent.com/71556213/161203742-71880161-1eea-4aac-8d66-604587f3c9f5.png">

But I want a clearer correspondence between the state and the spectral band, maybe something like this:
<img width="445" alt="example" src="https://user-images.githubusercontent.com/71556213/161204931-c9912adb-810d-423b-a0ea-32e5b513e529.png">

**Comment by vidaurre** [comment]
Hi, 

I think we can safely interpret a large p-value as non-significant. I guess a p-value of ~1.0 might be something to wonder about, though. 

About the second question, if I understand correctly, length(T) doesn’t match the number of rows in Y. For testing at the group level, Y has to have the same number of rows as subjects. I see there was a typo in the documentation of the function (where the dimensions of Y were described incorrectly). The documentation of the Wiki was correct.
