### ISSUE TITLE
Qusetions about spectbands() and analysis of results(FO/TP...)

### ISSUE THREAD

**Issue by ghost** [OHBA-analysis/HMM-MAR#77]
Hi, 

    I try to use the function to make band decomposition (spectbands() or spectdecompose()), and these functions results in a stuct with the spectral information across bands.
    1. If I only have 1 channel, it seems impossible to use spectdecompose(), because it doesn't have field 'coh'. I'd like to know it is reasonable to use specdecompose() with only one channel?
    2. If I want to assign two states to the same bands, is that possible? if it is possible to assign multiple states to one band, how to do it? And the analysis of other results corresponding to these states(such as FO/TP/Lifetime...) , does it make sense to add them directly or to add them by weight?
    3. I concatenate 4 subjects(one channel) and feed to TDE-HMM, if I want to get each subject's  getStateLifeTimes() or getStateIntervalTimes() by 'vpath', vpath is shorter than the data input, there is numsubs×embeddedlegs×2 timepoints less, in my case, it's 4×4×2, I want to know how to pad the vpath if I do this calculation, how to determine the time offset of each subject ?

Hoping for your reply.

**Comment by vidaurre** [comment]
Hi, 

1. You can't use coherence if there's only one channel, but you should be able to use the PSD, by specifying options.Base = 'psd'
2. I'm not sure I understand well, the NNMF method is applied across states (and regions) in a data-driven way to decompose frequency bins into frequency modes. So states are not "assigned", and it's not part of the current functionality to impose further constraints on the NNMF decomposition. 
3. You can use the function vpath_to_stc.m to transform vpath to a time x states matrix, and then padGamma.

Thanks d
