### ISSUE TITLE
Constant FO Issue with HMM MAR Toolbox

### ISSUE THREAD

**Issue by cogdishion** [OHBA-analysis/HMM-MAR#78]
Using a version of the toolbox downloaded before January 2021, we noticed that for a K-state HMM model applied to resting state timeseries of multiple subjects, the fractional occupancy (FO) of one state is always close to constant (0.0125) for all subjects. We have tried K from 4 to 16, and observed the same constant FO value of 0.0125 for one among K states. We suspect this state corresponds to the "deactive" state in your paper, but we are not sure. Our question is whether seeing a state with constant FO is expected, and whether we should remove all features, such as transition probability linked to this state, from subsequent analysis.

**Comment by vidaurre** [comment]
HI,

I think your intuition is right. This looks like the minimum threshold under which the state gets deactivated. I guess you could check this by setting options.dropstates = 1 (unless it's stochastic learning where this is not an option); if you do this, this shouldn't happen anymore.

Removing the state and the corresponding row/column from the transition probability matrix is a good idea.

Sorry for the delay, and hope that helps
d

**Comment by vidaurre** [comment]
This issue seems resolved. Reopen if necessary
