### ISSUE TITLE
Questions about metastate

### ISSUE THREAD

**Issue by Hongyao-Gao** [OHBA-analysis/HMM-MAR#79]
Dear Prof. Vidaurre,

I have some questions about the metastate described in your fantastic paper published in _PNAS_, 2017. I was hoping you might tell me how you calculated the fractional occupancy for each metastate and identified the spatial features for each metastate?

I did read the paper, but I am still confused with these questions.

I am looking forward to your reply. Thank you!

**Comment by vidaurre** [comment]
Hi —thanks

you can get the fractional occupancies with the getFractionalOccupancy.m function (see the Wiki for details), and then, if you apply PCA and get the first component, that would give you the "metastate index". 

The spatial features are just summaries. In that paper, I computed the degree (aggregated absolute correlation of each region with the rest of the brain) for those time points when the metastate is active. But there are other possibilities. 

Hope htat helps
d

**Comment by Hongyao-Gao** [comment]
Hi,

Thanks for your reply! I will take a try.
