### ISSUE TITLE
Bug in read_spm_file

### ISSUE THREAD

**Issue by cgohil8** [OHBA-analysis/HMM-MAR#81]
Recently getStateLifeTimes was changed (commit: 18ed6783eff47793df3dc12a8ecbace224d1fc48). read_spm_file calls getStateLifeTimes here: https://github.com/OHBA-analysis/HMM-MAR/blob/master/utils/general/read_spm_file.m#L24

Here: https://github.com/OHBA-analysis/HMM-MAR/blob/master/utils/analysis/getStateLifeTimes.m#L72-L76 you get an error: Reference to non-existent field 'dropstates'.

This can be resolved by adding: "if ~isfield(options,'dropstates'), options.dropstates = 1; end" to getStateLifeTimes.

**Comment by Wetiqe** [comment]
Hi, there is a function named `checkoptions` that can fill any missing fields in the struct `options`. 
`hmmmar.m`  called this function, so the struct `options` shouldn't contain any missing field.  


![image](https://user-images.githubusercontent.com/64966689/179364705-3fa15e3d-5cfb-4c5a-a3cd-0dba2e252d45.png)


To solve your problem, you can either run `function [options,data] = checkoptions (options,data,T,cv)` or simply use the following code from this function before you use `getStateLifeTimes.`
```
% Drop states? 
if ~isfield(options,'dropstates')
    options.dropstates = 0;
    %if any(~options.Pstructure), options.dropstates = 0;
    %else, options.dropstates = ~stochastic_learning; end
else
    if options.dropstates && options.nessmodel
        warning('nessmodel and dropstates are incompatible options')
        options.dropstates = 0;
    elseif options.dropstates && any(~options.Pstructure(:))
        warning('If Pstructure  has zeros, dropstates must be zero')
        options.dropstates = 0;
    elseif options.dropstates && stochastic_learning 
        warning('With stochastic learning, dropstates is set to 0')
        options.dropstates = 0;
    elseif options.dropstates && strcmpi(options.stopcriterion,'ChGamma')
        warning('With options.stopcriterion=''ChGamma'', dropstates is set to 0 ')
        options.dropstates = 0;
    end
end
```

Let me know if it still doesn't work.

**Comment by Wetiqe** [comment]
Could you post what file you are loading when you met this issue? 
The code you are quoting is only triggered when  `isvpath` is `True`. This shouldn't be the case when you use `read_spm_file` since this function is designed to load continuous data. 

```
function lifetimes = getStateLifeTimes (Gamma,T,options,threshold,threshold_Gamma,do_concat)
...
is_vpath = (size(Gamma,2)==1 && all(rem(Gamma,1)==0)); 
...
if is_vpath % viterbi path
    vpath = Gamma; 
    if options.dropstates==1
        K = length(unique(vpath));
    else
        K = options.K;
    end    
    Gamma = zeros(length(vpath),K);
    for k = 1:K
       Gamma(vpath==k,k) = 1;   
    end
```
```
function [X,T] = read_spm_file(spm_file,mat_file)
% Load an (continuous data) SPM file with filename specified in the spm_file  
% input parameter, and put the data into X in matrix format ready to be used by 
% the HMM. 
```

**Comment by vidaurre** [comment]
This issue seems solved  or inactive. Please reopen if necessary.
