### ISSUE TITLE
Missing `plot4paper` function in `STRM.m`

### ISSUE THREAD

**Issue by wsgriggs2** [OHBA-analysis/HMM-MAR#83]
Hi,
I am interested in testing your STRM-classification model on my data and was trying to work through your example script `STRM.m`. The `plot4paper` function is commonly called, but it is missing from the repo. From what I can tell, it just labels the axes, but was wondering if you could add this missing function into the repo?

**Comment by CameronHiggins** [comment]
Hi there, thanks for the message. This function is now included in the repository, please synchronise to the latest version.
