### ISSUE TITLE
Free energy computation for model selection

### ISSUE THREAD

**Issue by ateshkoul** [OHBA-analysis/HMM-MAR#84]
Dear Dr. Vidaurre,
I would like to use the free energy computation for model selection. Using my EEG data and estimating a Gaussian model on power time courses from all channels, I find that all the estimations of free energy are negative. I was wondering if this is normal and if so, what would constitute a lower value (lower absolute value or lower negative value). I also had a look at the past GitHub issue #45 .However, I don't think I fully understood the answer. I am also planning to use your suggestions (from the GitHub) on deciding on the number of states using data splitting.

Thanks a lot for your help,
Best regards,
Atesh

**Comment by vidaurre** [comment]
Hi Atesh,

You are right, the free energy shouldn't be negative. The reason why it happens here is that a constant is off. What matters (and what indicates that the inference is running fine) is that it goes systematically down during the inference. 

Currently I'm working on porting the toolbox to Python, so unfortunately I can't dedicate a lot of time to code maintenance unless it affects the functionality. This is thankfully not the case here.

You could still use the free energy to decide the number of states, but, as you pointed out, replicability in half-splits is recommended. 

Best,
d

**Comment by ateshkoul** [comment]
Dear Dr. Vidaurre,
Thanks for your response. Just to clarify, when you mean that the free energy is going down, you mean that the negative value is getting more negative or instead that the absolute value is decreasing.

It would be really nice to have a python ported version of the toolbox!

Thanks again,
Best regards,
Atesh
