### ISSUE TITLE
Specifying data from different trials of the same subject

### ISSUE THREAD

**Issue by ateshkoul** [OHBA-analysis/HMM-MAR#85]
Dear Dr. Vidaurre,
I am working with 64 channel EEG data and was wondering if there is a way to specify data from different trials from the same subject. At the moment, I am concatenating all the trials as if they were different subjects (in the variable T).

Thanks a lot for your help,
Best regards,
Atesh

**Comment by vidaurre** [comment]
Hi Atesh, 

For the sake of the HMM inference, the only thing that matters is where the signal has a breakpoint. That is, the HMM inference does not take into account whether this breakpoint corresponds to a change of trial, session or subject. (Unless you are using stochastic inference —then "batches" are made of a subset of subjects, but let's assume that's not the case here). 

Therefore, if you have your sessions partitioned in trials, such that there is some time between the trials but you don't care about the signal in these between-trial segments, then you can just concatenate the trials along the first dimension of X, and set T = total_number_of_trials * ones(length_of_one_trial). I think this is what you are doing.

That is possible, but unless the "task time" is very sparse within the session (i.e. if the time between the trials is too long) I think it's better to run the HMM continuosly on sessions without chopping them (i.e. T has one element per session), and then epoch the HMM state time courses afterwards. 

Does this respond to your question?
Thanks
d

**Comment by vidaurre** [comment]
I'm closing this assuming it's solved. Please reopen if necessary

**Comment by ateshkoul** [comment]
Dear Dr. Vidaurre,
Thanks a lot for your response. Yes, indeed this is how I am doing it currently.
Thanks again,
Best regards,
Atesh
