### ISSUE TITLE
New error in hmmdecode

### ISSUE THREAD

**Issue by sophieraible** [OHBA-analysis/HMM-MAR#88]
Hi Diego,

thank you for the quick fix and explanation about my previous problem. I updated the toolbox, but encountered a new error: When running `hmmdecode` with the updated version (again, with the HMM trained in the previous version), it throws the error below. Again, the 2019 version runs without errors. 

```
Error using sum
Invalid data type. First argument must be numeric or logical.

Error in checkGamma (line 7)
if any(isnan(sum(Gamma,2)))

Error in hmmsdecode (line 68)
        checkGamma(gamma,Ti,hmm_i.train,i);

Error in hmmdecode (line 76)
        [Path,Xi] = hmmsdecode(data,T,hmm,type);
```

Since I need to use the HMM trained in the old version I am wondering, does it make sense to simply stick to that version? Or do you recommend using the updated one (a lot of things probably changed since then)? Thank you again for your help!

**Comment by vidaurre** [comment]
Hi, sorry for the delay. 
At the moment I'm in the process of porting everything to Python, so unfortunately I am not able to fix things unless they are major. 
Just a question, if you run hmmsdecode on an HMM trained on the same (newest) version, does it complain?
Thanks
d
