### ISSUE TITLE
Problems with statistical tests

### ISSUE THREAD

**Issue by sophieraible** [OHBA-analysis/HMM-MAR#89]
Hi Diego,

I encountered another problem: I tried running the example script (run_HMMMAR_2.m) both with the current version of the toolbox and an old version from 2019. With the current version, `hmmtest` complains about the format of the design matrix Y:

```
Error using hmmtest (line 217)
Y must have as many rows as subjects, in this case 25

Error in run_HMMMAR_2 (line 128)
    t = hmmtest(Gamma{i},T,Tsubject,Y,options_test,hmm);
```

I am confused by this error, as the example script runs just fine with the old version of the toolbox (throws another error down the line but HMM test works smoothly), but maybe the way that hmmtest works was updated in the meantime. Note that I did not change anything in the example script, so Y has 100 rows (25 subjects * 2 sessions * 2 conditions). Ultimately, I will need to provide a design matrix with two sessions per subject (pre-/post-intervention) for my own data. Could you explain to me how to correctly format the design matrix?

**Comment by vidaurre** [comment]
Hi Sophie, 

I have revisited the hmmtest routine now. Indeed the function could not handle the case posed at the run_HMMMAR_2.m script: having one "trait" per subject , a number of sessions higher than one per subject, and wanting a group-level test. I wrote the code for that now, and fixed some little other things. 

I will update the repository shortly. 

thanks for pointing this out. 
d
