### ISSUE TITLE
HMM Classification Problem

### ISSUE THREAD

**Issue by lea231** [OHBA-analysis/HMM-MAR#90]
I am learning hidden Markov models, and thank you for your toolbox which provides a very convenient way to implement a hidden Markov model. I have some questions about the use of hidden Markov models for classification. I have two sets of data and trained the HMM model on each of them. I want to classify by calculating the probability of the test sequence occurring under the two models. Maybe this problem can be solved by a forward algorithm, but I'm not sure which parameter in the hmm structure corresponds to the observed probability or emission probability of the model? Or does HMM-MAR have a direct function to obtain the probability of a given new observation sequence occurring in a trained HMM model?

**Comment by vidaurre** [comment]
Hi Lea —thanks for your message. 

If I understand correctly, you have an HMM per group, and then, on a new subject, you want to know which HMM of the two fits the data best. That can be done with the forward -backward algorithm indeed: 

L = hmmlikelihood(new_data,T,hmm1);
Gamma = hmmdecode(new_data,T,hmm1);
likelihood1 = sum(sum(Gamma .* L))

L = hmmlikelihood(new_data,T,hmm2);
Gamma = hmmdecode(new_data,T,hmm2);
likelihood2 = sum(sum(Gamma .* L))

Hope that helps
d

**Comment by lea231** [comment]
Thank you Diego. Your answer is very helpful to me.

Best wishes and have a nice day.
