### ISSUE TITLE
Question about the correction of covariates before state estimation

### ISSUE THREAD

**Issue by Domi0222** [OHBA-analysis/HMM-MAR#91]
Thank you for your toolbox, which provides a very convenient way to implement a multivariate autoregressive hidden Markov model.

In my understanding, group differences in fractional occupancies and switching rates are calculated after state estimation, and the removing confounding factors, such as sex, age, and site, are conducted using GLM. I speculate that the covariates also affect the state estimation. Especially the multi-site data may have a strong effect on the BOLD signals, which leads to the possibility of estimating the site-specific state.

Given the above case, I think the first-level time series should be corrected using some methods (such as the state-space model), not only the regress out when estimating group differences. In my opinion, the time series model, including the fixed effect and random effect of confounds, was one solution (This could be an extension of ComBat for time-series: https://www.sciencedirect.com/science/article/pii/S1053811917306948).

What do you think about this point?
I'd be grateful if you could reply.
Best wishes,

**Comment by vidaurre** [comment]
Hi, 

You are right that estimation is not safe proof of confounds —specifically site-specific characteristics. So I agree that the  first-level time series should be corrected using the best methods available. 

However, the toolbox only provides very basic preprocessing functions, e.g. normalising, filtering, etc, and I feel that more sophisticated preprocessing options are beyond the scope of the software. 

Thanks for for the pointer, though, and stay tuned for the upcoming Python toolbox :) 
d

I chose not to include
