### ISSUE TITLE
Error in utils/preproc/highdim_pca

### ISSUE THREAD

**Issue by saltwater-tensor** [OHBA-analysis/HMM-MAR#93]
"" CODE BLOCK
if ~isempty(B)
    if varimax
        if isstruct(X)
            B = bsxfun(@minus,X.X,mean(X.X)) * A;
        else
            B = bsxfun(@minus,X,mean(X)) * A;
        end
    else
        B = B(:,1:ncomp);
    end
end    

[~,jj] = max(abs(B));
for j = 1:ncomp
   if B(jj(j),j) < 0
       B(:,j) = -B(:,j);
       A(:,j) = -A(:,j);
   end
end

"

Line 162: [~,jj] = max(abs(B)) to line 168

This section of the code should be within the if ~isempty(B) conditional block that begins at Line 150.

Otherwise it will produce an error.

**Comment by vidaurre** [comment]
Many thanks for pointing this out. The bug was introduced recently. I have fixed it now.
