### ISSUE TITLE
Error in tudadecode

### ISSUE THREAD

**Issue by saltwater-tensor** [OHBA-analysis/HMM-MAR#96]
This is what MATLAB command window shows:
-----------------------------------------------------------------------------------------------------------------------------

Y_is_continuous is not a recognized option
Warning: In order to use stochastic learning, BIGNbatch needs to be specified - running standard inference 
> In hmmmar (line 52)
In tudadecode (line 137) 
Index in position 2 is invalid. Array indices must be positive integers or logical values.
Error in hmmhsinit (line 112)
                    hmm.Dir2d_alpha(k,kk,i) = 1;
Error in hmmmar (line 431)
        hmm = hmmhsinit(hmm);
Error in tudadecode (line 137)
[~,Gamma,~,vpath] = hmmmar(Z,T,options); 

-----------------------------------------------------------------------------------------------------------------------------

**Comment by saltwater-tensor** [comment]
I think the problem is that hmmhsinit is not coded to handle Pstructure and Pistructure with zeros in it.

**Comment by saltwater-tensor** [comment]
> I think the problem is that hmmhsinit is not coded to handle Pstructure and Pistructure with zeros in it.

This cannot be true as hmmhsinit is used in training as well.

On deeper inspection the problem turns out to be that options.Pstructure remains to be a logical variable during training but when using tudadecode during the call to hmmhsinit, options.Pstructure becomes double type.

**Comment by vidaurre** [comment]
Hi, 
I have to admit I'm myself a little confused about this error, and I'm not being able to replicate it. 
Would you have a snippet of code I could use to raise the error? 

Meanwhile I have changed in hmmhsinit :   
kk = hmm.train.Pstructure(k,:);
to
kk = (hmm.train.Pstructure(k,:)==1);

which it seems it should fix the error

**Comment by saltwater-tensor** [comment]
I will update my local repository and let you know.

**Comment by vidaurre** [comment]
Hi, I'm closing this as I assume it's solved
