### ISSUE TITLE
MTIMES (*) is not supported

### ISSUE THREAD

**Issue by saltwater-tensor** [OHBA-analysis/HMM-MAR#97]
Trying to fit the TUDA model in decoding mode.

Options are set as follows:

    options.K = 4;
    options.Fs = 500;
    options.covtype = 'full';
    options.tol = 1e-5;
    options.cyc = 100;
    options.inittype = 'hmmmar';
    options.initrep = 5;
    options.initcyc = 50;
    options.repetitions = 1;
    options.updateGamma = 0;
    options.decodeGamma = 0;
    options.useParallel = 0;

    % Decoding
    options.encodemodel = false;

The call to fit the model is as follows:
[tuda,Gamma] = tudatrain(data_matrix,speed_matrix,time_matrix,options);

data_matrix : 4480239x2 double
speed_matrix: 4480239x1 double
time_matrix: Each entry in this vector contains the length of the trial.

Error generated:

cycle 1 free energy = 3.25195e+07 
Error using  * 
MTIMES (*) is not supported for one sparse argument and one single argument.
Error in updateW (line 219)
                muW = hmm.state(k).W.S_W(validentries,validentries)*temp(:);
Error in obsupdate (line 31)
            [hmm,XW] = updateW(hmm,Gamma,residuals,XX,XXGXX,Tfactor);
Error in hmmtrain (line 156)
        hmm = obsupdate(Gamma,hmm,residuals,XX,XXGXX);
Error in hmmmar (line 479)
        [hmm,Gamma,Xi,fehist] = hmmtrain(data,T,hmm,GammaInit,residuals,fehistInit);
Error in tudatrain (line 155)
    [tuda,Gamma,~,vpath] = hmmmar(Z,T,options);
Error in hmm_decoding_test (line 151)
[tuda,Gamma] = tudatrain(data_matrix,speed_matrix,time_matrix,options);

**Comment by saltwater-tensor** [comment]
I suspect it has to do something with the size of the dataset being used.

**Comment by vidaurre** [comment]
Hi, I have tried to replicate this but I couldn't. I could run the following code, analogous to yours, with no problem:

options = struct();
options.K = 4;
options.Fs = 500;
options.covtype = 'full';
options.tol = 1e-5;
options.cyc = 100;
options.inittype = 'hmmmar';
options.initrep = 5;
options.initcyc = 50;
options.repetitions = 1;
options.updateGamma = 0;
options.decodeGamma = 0;
options.useParallel = 0;

% Decoding
options.encodemodel = false;

data_matrix = randn(1000,2);
speed_matrix = randn(1000,1);
time_matrix = [500 500];

[tuda,Gamma] = tudatrain(data_matrix,speed_matrix,time_matrix,options);

**Comment by saltwater-tensor** [comment]
Hi,
So there are two things here:
1) The size of the dataset that you used for testing is much smaller than what I had used
2) When I use stochastic gradient based training the error goes away (while the size of my dataset is the same)

Hence I feel the problem is when the size of the dataset is large and stochastic updates are not used.

Then in the code there is something that forces Matlab to use sparse matrices and hence the error.

I also do not get any errors when the size of the dataset is relatively smaller.

**Comment by vidaurre** [comment]
Hi, I'm going to solve this issue because we are about to release a new Python toolbox that focuses on the implementation of TUDA and related models. We will support that one instead of hte Matlab one for this kind of analysis. 

If there's anything specific you want to discuss again, please reopen the Issue
